### ISSUE TITLE
[城中村群租房] -> [可可托海没有海]

### ISSUE THREAD

**Issue by lijiakaijun** [saveweb/doing#10]
ID:198
https://www.darmau.com
在[archive.org](https://web.archive.org/web/20210125081225/https://www.darmau.com/)上似乎找不到联系方式，只有一个公众号

域名状态如下 ~~，看来域名还没过期~~
![image](https://user-images.githubusercontent.com/55282876/121783036-3575f300-cbdf-11eb-9562-479504124478.png)

**Comment by yzqzss** [comment]
网站重新上线了，看起来是博主主动恢复的。

**Comment by yzqzss** [comment]
@Darmau

**Comment by yzqzss** [comment]
虽然博主的博客重新上线了，但是图片都404了...
![图片](https://user-images.githubusercontent.com/30341059/125278745-b0007280-e345-11eb-8da2-2e1344f626e8.png)

**Comment by yzqzss** [comment]
@Darmau 博主，您博客的图片都404了。

**Comment by yzqzss** [comment]
现在又变成站点无法访问的状态了。

已通过微信公众号询问博主，等待回复。

**Comment by yzqzss** [comment]
darmau.com: 该域名现已过期两个月。

**Comment by yzqzss** [comment]
昨日再次尝试通过微信公众号联系博主，仍然没有得到回复。
考虑到博客后期文章似乎和公众号上的相同，估计博主是回到公众号上输出内容了。
不过公众号上只同步发布了博客的部分博文，所以：
该博客进入saveweb存档流程。

**Comment by yzqzss** [comment]
微信公众号上得到回复，大致信息：

- 关站原因似乎是：网站/服务器每月花费太高。（100+）
- 有重建博客的打算，但是想先解决费用问题。
- 之前的博客文章、图片等数据均有备份。

**Comment by yzqzss** [comment]
~~公众号“城中村群租房”已注销。~~
没注销，换了名字：“可可托海没有海”

**Comment by darmau** [comment]
作者来了。目前换了新的架构开发了一个网站，目前在走备案流程，只对境外访问解析。国内的要么挂梯子要么等一阵子。

新域名：https://darmau.design/

文章正在往上搬。但以前的文章现在看着都羞耻，不一定全搬。。。

**Comment by yzqzss** [comment]
@Darmau 

![image](https://user-images.githubusercontent.com/30341059/194228388-4b34d36c-5581-42e5-8d5d-3ad63b2e6771.png)

![image](https://user-images.githubusercontent.com/30341059/194228201-9f5b49bc-b8e5-45c6-98f1-e408aba3889f.png)

RSS 的文章链接和标题都有错误。

---
Update: 已修复。

**Comment by yzqzss** [comment]
BOX 已更新：

> 名称：[城中村群租房] -> [可可托海没有海]
> URL：https://www.darmau.com/ -> https://darmau.design/
> RSS: https://darmau.design/rss.xml

---
这个 issue 开了快一年半了，终于关闭了！
@gledos @lijiakaijun @Darmau 庆祝！

**Comment by lijiakaijun** [comment]
@yzqzss 什么陈年老 issue 被解决了草（doge）
