### ISSUE TITLE
[大魔头闪电]/[鹏.]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#100]
### ID:790
https://ljp.me (http访问会显示宝塔的“没有找到站点”) 或 https://fyljp.com
#### 出现了什么问题：
ljp.me 无法访问。
fyljp.com 无内容。

---

@fyljp

**Comment by thangpai** [comment]
现情况：

**Comment by yzqzss** [comment]
@fyljp

请问，您的博客是数据丢失了吗？以前的文章都没了。

**Comment by 1C8199D3C9F1** [comment]
后面那个网站已经可以正常访问了，但是文章还是没有多少。

**Comment by fyljp** [comment]
神奇的项目哈哈
前者 https://ljp.me 放弃不再使用
目前内容全部清空，重新来过吧

**Comment by yzqzss** [comment]
已更新Feed： https://fyljp.com/index.xml
box见： https://box.othing.xyz/i/?get=f_790

不过hugo的rss生成器似乎有问题，RSS获取的文章都不带换行的。找时间去hugo那边看看。
