### ISSUE TITLE
[Chores]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#101]
### ID:448
https://blog.raincorn.top/
#### 出现了什么问题：
https无法访问，http访问会跳转到wordpress安装页面。
![图片](https://user-images.githubusercontent.com/30341059/134793920-1d165e2d-3ab3-4136-8e13-14ddeaa4329a.png)

据观察，博主前几天把博客地址[改为 old.raincorn.top](https://github.com/rainvalley/rainvalley.github.io/commit/edf5093751e27def3a02b25266a2438a11bc3a1c) ，估计是blog.* 会变成新博客:
https://github.com/rainvalley/rainvalley.github.io

@rainvalley

**Comment by rainvalley** [comment]
谢谢提醒，已经改回blog* ，新博客将直接使用根域名。

**Comment by yzqzss** [comment]
@rainvalley

看起来您似乎准备保持使用 blog.* 。
此issue关闭。

**Comment by yzqzss** [comment]
Update: https://blog.raincorn.top/ -> https://raincorn.top/
BOX已更新： https://raincorn.top/atom.xml
