### ISSUE TITLE
[Jay Zangwill的博客]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#106]
#### 出现了什么问题：
- https://www.jayzangwill.cn SSl证书过期。
- 主页打开是空白

---

@JayZangwill

**Comment by thangpai** [comment]
主页的空白我这里没有体现，或许您那边有问题。

**Comment by yzqzss** [comment]
博客实际地址为: https://jayzangwill.github.io feed:https://jayzangwill.github.io/atom.xml

已更新。

**Comment by thangpai** [comment]
订阅feed地址错误，应为https://jayzangwill.github.io/blog/atom.xml 。

**Comment by yzqzss** [comment]
@thangpai 已改。

**Comment by 1C8199D3C9F1** [comment]
网页出现域名过期报错。

**Comment by yzqzss** [comment]
介于[博主Github](https://github.com/JayZangwill)近一年未活动，已将其Repo[加入存档](https://github.com/saveweb/Auto-backup-repo/commit/ceb86509160dddb69d5f2e308f2d28524756d9c3)。

**Comment by 1C8199D3C9F1** [comment]
已发送Email，等待回复。
---
如果三日内不回复再使用QQ尝试加好友联系。

**Comment by JayZangwill** [comment]
https://jayzangwill.github.io/blog/
后面使用这个地址吧

**Comment by yzqzss** [comment]
> https://jayzangwill.github.io/blog/ 后面使用这个地址吧

好的。([box已更新](https://box.othing.xyz/i/?get=f_372))
