### ISSUE TITLE
[Y同学]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#114]
### ID:989
https://eron.couqiao.xyz
#### 出现了什么问题：找不到ip地址
查了下域名，是明年1月过期
但现在访问显示找不到ip

https://github.com/saveweb/doing/issues/9

**Comment by 1C8199D3C9F1** [comment]
下面是个人查询结果：

Y同学的最后活动日期：https://typesns.com/cat/7
但这里没有留任何联系方式。

已经先发好友网站留下的QQ号的email的试图取得联系，如果还是取得不到联系，我再去上面的网站注册帐户尝试联系。

Y同学这个人的couqiao.xyz域名有两个博客，还有个allen.couqiao.xyz，archive等没有快照信息，但Google有搜索结果。

**Comment by yzqzss** [comment]
邮件得到回复：
`目前在整理，服务器转移，过段时间就会重新上线。`

**Comment by yzqzss** [comment]
邮件得到回复：
> `已更新   新地址https://blog.couqiao.top`

box已更新feed链接为：https://blog.couqiao.top/feed/
