### ISSUE TITLE
[Binz’s Blog] > [Stitch's Blog]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#12]
ID:10
https://blog.gaobinzhan.com/
宕机

![图片](https://user-images.githubusercontent.com/30341059/121793042-eacf9780-cc2d-11eb-8dd0-2cf5c94ec234.png)

**Comment by yzqzss** [comment]
@Stitch-June

**Comment by Stitch-June** [comment]
我正在部署新的域名

**Comment by Stitch-June** [comment]
原来的被我舍弃了

**Comment by Stitch-June** [comment]
这个组织是干嘛的 🤔️

**Comment by yzqzss** [comment]
> 
> 
> 这个组织是干嘛的

参见: https://saveweb.othing.xyz https://t.me/s/blogrsslist
1、存档网站 2、维护一个rss订阅源列表

**Comment by Stitch-June** [comment]
还能恢复？我数据被删了

**Comment by yzqzss** [comment]
> 
> 
> 还能恢复？我数据被删了

https://box.othing.xyz/i/?get=f_10 这里有博客最新的13篇文章，之前的没有，不全。
https://web.archive.org/web/*/https://blog.gaobinzhan.com archive上大部分都有。

我可以帮你把archive.org上的存档打包发给你。

**Comment by Stitch-June** [comment]
好谢谢

**Comment by Stitch-June** [comment]
你qq多少

**Comment by yzqzss** [comment]
> 
> 
> 好谢谢
> 你qq多少

2361769788

**Comment by yzqzss** [comment]
![图片](https://user-images.githubusercontent.com/30341059/123509686-7c68eb80-d6a9-11eb-99be-050585c27168.png)

备份已发，等待博主恢复博客。

**Comment by yzqzss** [comment]
update: 博主网站正在走备案

**Comment by yzqzss** [comment]
等了这么久了，忍不住了。帮博主迁移了文章，已发pr。
https://github.com/Stitch-June/Stitch-June.github.io/pull/12

**Comment by yzqzss** [comment]
已更新地址: [Stitch's Blog](https://stitch.cn/) 
Feed:https://stitch.cn/atom.xml
