### ISSUE TITLE
[beyond stars]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#121]
#### 出现了什么问题：
https://exploro.one/ 宕机，（Cloudflare 开了 Always Online）

**Comment by yzqzss** [comment]
`502 Bad Gateway`

**Comment by yzqzss** [comment]
> 旧有的基于 React 方案的前端因为作者兴趣转变不再维护。--[关于本站- notion](https://hsiaofongw.notion.site/4837f709e1044164aed3e12a3046813f) 

博主使用 Notion 去了。

---
@hsiaofongw 两个 feed 链接都 502 了：

- https://exploro.one/feed/atom
- https://exploro.one/posts/index.xml

**Comment by cmpxchg16b-nop** [comment]
修好了，感谢反馈！
