### ISSUE TITLE
[多半不走运]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#122]
### ID:431
https://www.likelyunlucky.xyz/
#### 出现了什么问题：
`Error establishing a database connection`

---

@faceyoung

**Comment by yzqzss** [comment]
已恢复。

**Comment by 1C8199D3C9F1** [comment]
发生了什么问题：

打开后不是博主的网站，英文显示一个社交网站页面。

---

@faceyoung

**Comment by yzqzss** [comment]
> 打开后不是博主的网站，英文显示一个社交网站页面。

这是一个分布式[SNS系统](https://friendi.ca/)。

**Comment by yzqzss** [comment]
与#151 重复。
