### ISSUE TITLE
[wys.me]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#124]
#### 出现了什么问题：
https://www.wys.me/894.html :
```
这个博客将于2021年12月31日23:59:59正式关闭。当前在用的网站服务器将于2022年3月9日 23:59:59到期，到期后计划换个境外虚拟主机挂那个CRM。之后的网络生活中，本人将只保留一个CRM站点，其余统统关闭。
```

博主准备关站。

**Comment by yzqzss** [comment]
感谢来自[Telegram-UID:2024941400]的提交: https://t.me/saveweb_chat/492

**Comment by yzqzss** [comment]
询问博主，得知：
“主意还没改变，年底就关。”

**Comment by yzqzss** [comment]
https://www.wys.me/894.html#comment-5751:
`嗯，数据会保存到家里的电脑和移动硬盘两个地方。如果那一天舆论形式有所改变，有可能恢复原站点，或是重建一个类似于（只有一个作者的、只有一期的与日志有很大不同的）电子期刊杂志的站点。`

**Comment by 1C8199D3C9F1** [comment]
网站公告：
“wys.me”博客停止公开访问公告：亲爱的博客朋友，与大家一同走过11年（以姓名全拼域名wangyushuang.com注册时间为准），是时候说再见了。由于个人原因，从2021年12月31日23时59分59秒开始，“wys.me”博客停止公开访问，施行凭密钥访问，作为一个人的历史记载，私人空间里的日志会保持更新。 再见了，各位曾经风雨同行的博友们！【你若想我（的博客）了，可给我发E-mail获取访问密钥（密钥每月更新1次），密钥专用邮箱：my@wys.me。】

**Comment by yzqzss** [comment]
考虑到博主公告中说的：“停止公开访问，施行凭密钥访问，作为一个人的历史记载” 且 “数据会保存到家里的电脑和移动硬盘两个地方”
我们就不对其存档了。

**Comment by 1C8199D3C9F1** [comment]
wys博主在调试自己的网站，根据以往的记录可能是在调试CRM系统。BLOG可能真的到墓场的时候了。（原先的RSS订阅查看网站也一起关掉了）

来源：
saveweb/doing#124
box上的933期的第五条。

**Comment by 1c8199d3c9f1** [comment]
现在的情况：

wangyushuang.com使用HTTP可正常访问。HTTPS会显示售卖页面。

**Comment by 1c8199d3c9f1** [comment]
现在的情况：

wangyushuang.com已无CRM系统管理页面，直接可以访问。

**Comment by yzqzss** [comment]
现可无需密码正常访问，恢复正常。

**Comment by N-628** [comment]
现在需要通过密码访问了。

**Comment by yzqzss** [comment]
博主又开始用 www.wys.me 写博客了，以前的文章没有迁移，从0开始。
