### ISSUE TITLE
[LeftShadow | 影留]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#126]
#### 出现了什么问题：
Warning: preg_replace(): Compilation failed: invalid range in character class at offset 4 in /www/wwwroot/leftshadow/wp-content/plugins/crayon-syntax-highlighter/crayon_langs.class.php on line 340

PHP报错。

**Comment by 1C8199D3C9F1** [comment]
联系了博主email，得到回复：
php 版本太高了，退回去了，感谢反馈。
