### ISSUE TITLE
[Eltrac's] -> [考拉咖啡馆]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#127]
### ID:489
https://blog.guhub.cn/
#### 出现了什么问题：
博主准备全新开始：[请重新认识我——一只孤独的考拉 - 考拉咖啡馆](https://blog.guhub.cn/on-everything/start.html)
并将旧博客存档：https://old-blog.guhub.cn/

**Comment by 1C8199D3C9F1** [comment]
feed链接缺少了“/”。

**Comment by yzqzss** [comment]
@1C8199D3C9F1 box那边有 / ，但timqian/c-i-b 那边没有，改的时候没仔细看。
已经改了。
