### ISSUE TITLE
[Garfield Wang's blog]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#128]
#### 出现了什么问题：
https://gw2001.xyz/

站点清空，为目录索引状态。
![图片](https://user-images.githubusercontent.com/30341059/139563555-e027f039-8dd1-40fd-b788-91a9ad40e07e.png)

跑路也不至于把博客也弄一起跑路吧，你都换了多少个ID了……
快快回来！
:-(

**Comment by 1C8199D3C9F1** [comment]
这一个月比较忙，暂时为了防止打扰就暂时关停。恢复时间待定吧。马甲问题之后再处理。

**Comment by Garfield-Wang** [comment]
已经恢复博客。
