### ISSUE TITLE
[冰哥笔记]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#130]
### ID:1037
https://www.bgbiji.com/
#### 出现了什么问题：

似乎屏蔽了国际访问。

**Comment by gledos** [comment]
## 粗略检查

根据 17ce 境内访问测试来看，许多服务器都显示错误 501 。

![圖片](https://user-images.githubusercontent.com/23720620/141689778-43ce5921-6034-4903-b58c-a4e8be54ecf9.png)

DNS 看起来，可能尝试使用 CDN，但未生效。

![圖片](https://user-images.githubusercontent.com/23720620/141689929-40f9cc7a-9b6a-44a1-b0eb-e1673940be5e.png)

ping.pe 完全无法访问该网站，即使是境内服务器也是如此。

![圖片](https://user-images.githubusercontent.com/23720620/141689965-338f1464-9716-45c8-9765-71f2dd14147c.png)

**Comment by yzqzss** [comment]
本地电信4G，能正常访问该博客。
![Screenshot_20211115_005857_org mozilla firefox](https://user-images.githubusercontent.com/30341059/141690586-06f61c79-ce68-42f4-b1a2-99608b0fe109.jpg)

**Comment by 1C8199D3C9F1** [comment]
不确定设置HOSTS能否解决问题。
211.149.140.132 bgbiji.com
211.149.140.132 www.bgbiji.com

**Comment by yzqzss** [comment]
目前，境内与境外访问似乎已恢复正常。（boce.com ping.pe 均正常）
box也能正常获取到RSS文件。
