### ISSUE TITLE
[开源之心]

### ISSUE THREAD

**Issue by 1C8199D3C9F1** [saveweb/doing#132]
### ID:796

http://sht2019.cn

#### 出现了什么问题：

貌似对国际访问进行了屏蔽。

同样情况：#130

**Comment by gledos** [comment]
DNS 情况与 #130 确实相似:

![圖片](https://user-images.githubusercontent.com/23720620/142132595-cf98e001-9a27-4c83-bd4a-080c2f77258d.png)

DNS 服务器也是 myhostadmin.net 的，也许应该检查 myhostadmin.net 是否更新了政策。

**Comment by 1C8199D3C9F1** [comment]
该CDN域名信息表明隶属于西部数码。
可能是西部数码该域名的CDN的问题。

——————————————————————
下面是我个人分析，可能有问题：

    我个人直接针对了CDN网站搜索，发现了部分网站设置CNAME的快照。
    那些网站曾经设置了冰哥笔记同样的CNAME，后期换了一个其他的CNAME，是ssl4.my.800cdn.com 。
    我个人尝试通过了gledos使用的ping.pe网站对 ssl4.my.800cdn.com <http://ssl4.my.800cdn.com> 进行PING，国际上也可通畅，估计这个PING的IP通过设置HOSTS可以达到打开的效果。（我个人本机在国内是可以通的。）
    如果你的BOX是在境外的话，可以尝试HOSTS试试看是否能打开。
    -------------------------------------------------------------------
    其他信息：
    该CDN是属于西部数码的，通过WHOIS可以看到。
    这个是发现根据的一个网站（该网站貌似是个商业网站）：
    https://www.dnsgrep.cn/subdomain/24shifu.com








2021年11月17日 下午12:04 来自 ***@***.***:

**Comment by yzqzss** [comment]
目前，境内与境外访问似乎已恢复正常。（boce.com ping.pe 均正常）
box也能正常获取到RSS文件。
