### ISSUE TITLE
[Jacky Tong]

### ISSUE THREAD

**Issue by 1C8199D3C9F1** [saveweb/doing#133]
### ID:836

http://www.jackytong.com/

#### 出现了什么问题：

访问该网站，显示如下报错：

`该网站未根据工信部相关法律进行备案。`

**Comment by 1C8199D3C9F1** [comment]
已对博主发送Email邮件，等待回复。

**Comment by 1C8199D3C9F1** [comment]
已恢复。

**Comment by yzqzss** [comment]
> 

已移动分类。
