### ISSUE TITLE
[iNote]

### ISSUE THREAD

**Issue by 1C8199D3C9F1** [saveweb/doing#134]
### ID:290

https://inote.xyz

#### 出现了什么问题：

RSS链接显示404 NOT FOUND错误。还伴随其他报错提示出现。

![iNote错误提示](https://user-images.githubusercontent.com/94344766/142005724-f73b8e48-63da-4bf7-ad32-dcffd22d5931.png)

**Comment by yzqzss** [comment]
https://inote.xyz/rss.xml

这个RSS链接正常，不过这个RSS链接可能不是博主想提供的。（RSS中包含全部博文）
见：![inote.xyz`s feed](https://img.othing.xyz/imgs/2021/01/c8e1cfe4b9a11be9.jpg)

自此之后，博主只提供最近10篇文章的RSS。（ https://inote.xyz/rss/ ）

**Comment by 1C8199D3C9F1** [comment]
BOX里的RSS地址是错的。

**Comment by yzqzss** [comment]
> 
> BOX里的RSS地址是错的。

我知道，但是“正确的” rss.xml 有 157kb ，博客的全部文章和页面都包含在里面。

可能要提醒博主：他的RSS输出太大了，CDN流量可能增加。

**Comment by yzqzss** [comment]
Solved.
