### ISSUE TITLE
[桃园]

### ISSUE THREAD

**Issue by 1C8199D3C9F1** [saveweb/doing#136]
### ID:241

http://www.taoweng.site

#### 出现了什么问题：

站点使用PING.PE进行PING测试，全部超时。

![PING PE截图](https://user-images.githubusercontent.com/94344766/142136902-165d3e3d-daf1-422f-a955-f28495b1847d.png)

**Comment by yzqzss** [comment]
@crazylxr 您的博客无法访问了。

**Comment by 1C8199D3C9F1** [comment]
已发送Email。等待回复。

**Comment by crazylxr** [comment]
服务器到期了，我准备用 github 打一个静态博客

**Comment by crazylxr** [comment]
已经建好了哈。

**Comment by 1C8199D3C9F1** [comment]
@crazylxr 博主，没有RSS订阅链接。

**Comment by yzqzss** [comment]
@crazylxr https://github.com/hexojs/hexo-generator-feed

**Comment by crazylxr** [comment]
https://www.taoweng.site/atom.xml 已经可以了哈

**Comment by yzqzss** [comment]
> https://www.taoweng.site/atom.xml 已经可以了哈

OK!
