### ISSUE TITLE
[足元注意]

### ISSUE THREAD

**Issue by 1C8199D3C9F1** [saveweb/doing#138]
### ID: 963

https://amcy.fm/

#### 出现了什么问题：

NOT FOUND错误。

![amcy](https://user-images.githubusercontent.com/94344766/142198822-0b4088a8-a2f0-4065-b5b1-bb80ec3aecc8.png)

**Comment by 1C8199D3C9F1** [comment]
@yorkxin 博主，您的播客網址發生了404錯誤。

**Comment by 1C8199D3C9F1** [comment]
已發e-mail，等待回復中。

**Comment by yzqzss** [comment]
已通过Telegram私信播主，等待回复。

**Comment by yzqzss** [comment]
https://github.com/yorkxin/podcast-utils/commit/026006a1e9a15e8cf712997fe42ef87d6acdfb2e

`Note: the author does not produce podcasts anymore. Expect no updates from this repository for the foreseeable time. `

看来至少两个月前播主就宣布不再制作播客了。

---

进入存档流程，尽量全文找音频文件。

**Comment by yorkxin** [comment]
@yzqzss 抱歉一直沒回覆。最近太忙了。

我前陣子決定把我的播客全部刪除，不希望繼續在任何管道發布。

但想不到會有人想要備份。

我不知道這個項目的目標是什麼，不過希望你們可以略過這個播客，尊重我的意願。

謝謝

**Comment by gledos** [comment]
博主已明确行使「[被遗忘权](https://en.wikipedia.org/wiki/Right_to_be_forgotten)」，此 issues 因此关闭。

**Comment by yzqzss** [comment]
@yorkxin 好的，请问[这个链接](https://box.othing.xyz/i/?get=f_963)里的内容需要删除吗？ 里面存有我们从您播客RSS获取到的item （不含音频文件，仅存有shownote、且该站点禁止搜索引擎抓取）。

另外， https://archive.org 上也保存有您的播客网址的[历史快照](https://web.archive.org/web/20210301014404/https://amcy.fm/)（同样不包含音频文件、且禁止搜索引擎抓取）。如果需要删除，可能得您自己联系archive.org。

以及，该issue和其它衍生信息需不需要删除？

**Comment by yorkxin** [comment]
@yzqzss @gledos  謝謝你們的理解。

請幫我把你們所儲存的 RSS 內容刪除。

至於其他歷史快照服務，我會個別去處理。

這個 issue 本身和其衍生信息留著沒關係。

再次感謝！

**Comment by yzqzss** [comment]
> 請幫我把你們所儲存的 RSS 內容刪除。

好的，已删。
