### ISSUE TITLE
[电脑博士]

### ISSUE THREAD

**Issue by 1C8199D3C9F1** [saveweb/doing#139]
### ID: 540

https://diannaobos.com/

#### 出现了什么问题：

1.FEED链接404错误。
2.网站里的资源链接被指向了127.0.0.1。

**Comment by 1C8199D3C9F1** [comment]
已通过发送Email联系，等待回复。

**Comment by 1C8199D3C9F1** [comment]
博主已回复：

`博客遇到了大问题导致。`

题外话：该邮件被放入了SPAM文件夹。

**Comment by gledos** [comment]
已确认网站恢复，DNS 设置目前恢复正常。

**Comment by gledos** [comment]
FEED 地址目前为: https://diannaobos.com/feed.php

内容正常。

**Comment by yzqzss** [comment]
Solved.
