### ISSUE TITLE
[Barkure]

### ISSUE THREAD

**Issue by 1C8199D3C9F1** [saveweb/doing#143]
### ID: 502

https://guguga.cn/

#### 出现了什么问题：

`该网站未根据工信部相关法律规则进行备案`

---

@barkure

**Comment by 1C8199D3C9F1** [comment]
已通过telegram私信，等待回复。

**Comment by yzqzss** [comment]
> 已通过telegram私信，等待回复。

我昨天已经联系过了，也在等回复。你撤回还是我撤回？

**Comment by 1C8199D3C9F1** [comment]
> > 已通过telegram私信，等待回复。
> 
> 我昨天已经联系过了，也在等回复。你撤回还是我撤回？

我已撤回。

**Comment by yzqzss** [comment]
得到回复：

```
备案
暂停解析了
```

**Comment by yzqzss** [comment]
```
barkure, [30.11.21 20:10]
备案成功，博客已上线
```
