### ISSUE TITLE
[Becomin' Charles]

### ISSUE THREAD

**Issue by awslblog** [saveweb/doing#145]
#### 出现了什么问题：
https://sexywp.com/ SSL证书已于11月27日过期

**Comment by 1C8199D3C9F1** [comment]
@charlestang 博主，您的博客SSL证书过期了。

**Comment by charlestang** [comment]
收到，谢谢，已经恢复。

**Comment by 1C8199D3C9F1** [comment]
> 收到，谢谢，已经恢复。

好的。

**Comment by awslblog** [comment]
> 收到，谢谢，已经恢复。

使用证书自动化是一个明智的选择。在方便的同时也更安全。

**Comment by charlestang** [comment]
明白，我是自动化的，三个月一换，这次不知道为啥，nginx 的 reload 失败了，没能加载新证书。
