### ISSUE TITLE
[@Lenciel]

### ISSUE THREAD

**Issue by awslblog** [saveweb/doing#149]
### ID: 316
https://lenciel.com/
#### 出现了什么问题：
SSL证书问题:未配置中间证书。
注意：该站点**在浏览器内访问正常**，`curl`报错，因为没配置中间证书。
论坛讨论帖 https://community.letsencrypt.org/t/curl-ssl-verify-error/166483/13
在线工具检查结果 https://decoder.link/sslchecker/lenciel.com/443
Chain Issues: |✘ The chain doesn't contain any intermediate certificates

**Comment by 1C8199D3C9F1** [comment]
@Lenciel

**Comment by lenciel** [comment]
修复了...thanks.
