### ISSUE TITLE
[Placeholder]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#15]
ID:151
https://www.luotaoruby.me
找不到存档，RSS上也没有文章
有对应上游 https://github.com/timqian/chinese-independent-blogs

**Comment by yzqzss** [comment]
@ya-luotao

**Comment by yzqzss** [comment]
@ya-luotao
emm，发现你将仓库设成private了...
既然这样，已将您的博客链接从本项目 (https://github.com/saveweb/rss-list/) 和上游 (https://github.com/timqian/chinese-independent-blogs) 中移除 。


![图片](https://user-images.githubusercontent.com/30341059/124380637-50c0b380-dcf0-11eb-8dee-82877d2ba59b.png)

----
附件：

https://saveweb.othing.xyz

纯公益项目。为已关站的博客建立存档/备份站点。

    如果有一天，当你对创作提不起兴趣，产生了关站的想法，并真要这么做了。可与我们取得联系。
    到时候您可以将您网站的全站备份发给我们，由我们为您的站点创建一个永久的存档站点。
    不管文章多少，我们都欢迎。
