### ISSUE TITLE
[aiokr's daily]; [呈像 PHOTUP] -> [瞬间 Press]; [摄万卷书]

### ISSUE THREAD

**Issue by awslblog** [saveweb/doing#150]
### ID:315
https://itypen.app/
#### 出现了什么问题：
SSL证书无效，并且开启了`HSTS`导致无法访问
certificate that is not valid for `itypen.app`. The certificate is only valid for the following names: `myportfolio.com, *.myportfolio.com`

**Comment by 1C8199D3C9F1** [comment]
博主，您的博客打不开了。发生了上面的错误。

---

@aiokr

**Comment by yzqzss** [comment]
补充，此前已订阅新博客站点：https://photup.art ID:1048
这个 ID:315 为旧站点，也许是被博主弃用了。

但新旧站点内容不一，请问博主 @aiokr 您是否会对旧站点的文章数据做迁移/存档处理？

**Comment by yzqzss** [comment]
修正，ID:315 博主有github存档repo：https://github.com/aiokr/iTypen-Pages

**Comment by yzqzss** [comment]
> ID:315 博主有github存档repo：https://github.com/aiokr/iTypen-Pages
> 此前已订阅新博客：https://photup.art ID:1048

介于此，BOX已删除ID:315。

**Comment by yzqzss** [comment]
> > ID:315 博主有github存档repo：https://github.com/aiokr/iTypen-Pages
> > 此前已订阅新博客：https://photup.art ID:1048
> 
> 介于此，BOX已删除ID:315。

博主[重启了](https://github.com/timqian/chinese-independent-blogs/pull/974)博客（老文章还在）。
BOX已订阅 ID:1270

另外， ID:1048 https://photup.art/ 和 ID:1270/315 https://tripper.press/ 文章有一定重合和缺失， @aiokr  ，请问你会关掉两个网站的其中之一吗？

**Comment by yzqzss** [comment]
得到回复：`photup.art预计之后会关闭`

之后会删除 ID:1048 ，保留 ID:1270 。

**Comment by yzqzss** [comment]
ID:1048 photup.art | Payment Required

已删除。
