### ISSUE TITLE
[多半不走运]

### ISSUE THREAD

**Issue by awslblog** [saveweb/doing#151]
#### 出现了什么问题：
certificate that is not valid for www.likelyunlucky.xyz. The certificate is only valid for likelyunlucky.xyz.
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by 1C8199D3C9F1** [comment]
打开貌似是一个个人搭建的网盘，不是博客。

---

@faceyoung

**Comment by yzqzss** [comment]
已在其 [Discord](https://discord.gg/cp7XuZ7Cuh) 询问。

**Comment by yzqzss** [comment]
@faceyoung 您的[博客](https://www.likelyunlucky.xyz/)无法访问了。

**Comment by yzqzss** [comment]
Face, [05.12.21 08:52]

朋友上我vps一通操作，域名和博客集体gg😂

yzqzss |一座桥在水上, [05.12.21 08:54]
博客备份数据都还在吧？

Face, [05.12.21 08:55]
木有…😓

---

博主表示要斟酌一下是否重开博客，下个月如果重开，会通知。
