### ISSUE TITLE
[城南旧事]

### ISSUE THREAD

**Issue by awslblog** [saveweb/doing#153]
### ID:899
http://blog.pho.ink/
#### 出现了什么问题：
HTTP 没有找到站点
HTTPS 证书名称不匹配，跳过提醒后404

**Comment by 1C8199D3C9F1** [comment]
可能是博主更换了地址。
从互联网档案馆发现11月20日跳转到了下列地址：
blog.loli.top
名称和之前是一样的。

**Comment by yzqzss** [comment]
box上面的地址就是 blog.loli.top 无需修改。
