### ISSUE TITLE
[己羊的梦]

### ISSUE THREAD

**Issue by awslblog** [saveweb/doing#154]
### ID:194
http://www.jiyang00.cn/
#### 出现了什么问题：该网站未根据工信部相关法律进行备案

@Jiyang00

**Comment by 1C8199D3C9F1** [comment]
#86

**Comment by 1C8199D3C9F1** [comment]
从搜索引擎查询到「已羊的梦」博客IP。暂时可通过IP访问blog。

**Comment by ghost** [comment]
Blog 地址：https://jiyang00.github.io/

**Comment by ghost** [comment]
BOX 上的 Blog 地址已更新。
