### ISSUE TITLE
[nojsja]

### ISSUE THREAD

**Issue by N-628** [saveweb/doing#155]
### ID: 1001

https://nojsja.github.io/blogs/
or
https://nojsja.gitee.io/blogs/

#### 出现了什么问题：

https://nojsja.github.io/blogs/atom.xml 地址已经失效。
博客仓库也没有订阅相关的XML文件。

**Comment by gledos** [comment]
![_config.yml](https://user-images.githubusercontent.com/23720620/145131268-d09bf8cb-1586-4fc5-b2cf-97f6f8e99fe3.png)

从博客的配置文件 [_config.yml](https://github.com/nojsja/blogs-hexo/blob/75e7d0d4fedbb07b2366444d63613e1a1ba88688/_config.yml#L204) 来看，博主应该是尝试开启 RSS ，但由于配置原因，目前访问 https://nojsja.github.io/blogs/atom.xml 会得到 404 。

![https://nojsja.github.io/blogs/atom.xml](https://user-images.githubusercontent.com/23720620/145131397-39efa281-4f29-4c55-9653-3776f3224a4c.png)

**Comment by yzqzss** [comment]
> ![_config.yml](https://user-images.githubusercontent.com/23720620/145131268-d09bf8cb-1586-4fc5-b2cf-97f6f8e99fe3.png)
> 
> 从博客的配置文件 [_config.yml](https://github.com/nojsja/blogs-hexo/blob/75e7d0d4fedbb07b2366444d63613e1a1ba88688/_config.yml#L204) 来看，博主应该是尝试开启 RSS ，但由于配置原因，目前访问 https://nojsja.github.io/blogs/atom.xml 会得到 404 。
> 
> ![https://nojsja.github.io/blogs/atom.xml](https://user-images.githubusercontent.com/23720620/145131397-39efa281-4f29-4c55-9653-3776f3224a4c.png)

他的博客实际仓库应该是：https://github.com/nojsja/blogs （没有index.xml） 可能不是： https://github.com/nojsja/blogs-hexo

**Comment by yzqzss** [comment]
移动分类：“纯技术类博客”==>“不提供RSS”

**Comment by 1C8199D3C9F1** [comment]
feed链接已经恢复正常。
