### ISSUE TITLE
[苍穹の下]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#158]
#### 出现了什么问题：
https://www.blueskyxn.com/feed/
RSS出错。
![图片](https://user-images.githubusercontent.com/30341059/145706817-1a53bb93-265c-492d-8c05-2ad0c75cb3f2.png)

---
@BlueSkyXN

**Comment by yzqzss** [comment]
已在其TG群组中[询问](https://t.me/c/1312154845/95365)。

**Comment by yzqzss** [comment]
得到回复：“`我也不知道原因`”
……

**Comment by 1C8199D3C9F1** [comment]
已恢复。
