### ISSUE TITLE
[Caos]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#159]
### ID:449
https://caos.me/
#### 出现了什么问题：
博主似乎准备将 https://github.com/caosbad/caosbad.github.io 迁移到 https://github.com/caosbad/notion-page 。
这导致了原RSS链接：https://caos.me/feed 的失效。
另外，原仓库的文章似乎还没有开始迁移。

---
@caosbad

**Comment by caosbad** [comment]
问题已经修复，旧文章不打算做迁移，新博客已经支持 RSS

**Comment by yzqzss** [comment]
@caosbad 好的。

**Comment by yzqzss** [comment]
RSS链接再次失效： https://caos.me/rss https://caos.me/feed

**Comment by yzqzss** [comment]
emm，又失效……

**Comment by yzqzss** [comment]
移动到“不提供RSS”分类。
