### ISSUE TITLE
[Lucien's Blog]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#167]
### ID:296
https://blog.lucien.ink/
#### 出现了什么问题：
SSL出错。

**Comment by yzqzss** [comment]
已在博主另一个生活博客上[留言提醒](https://www.lucienshui.cn/about.html#comment-17)。

**Comment by yzqzss** [comment]
SSL错误重现，已[再次留言](https://www.lucienshui.cn/about.html#comment-19)提醒。

**Comment by N-628** [comment]
博主，您的博客的 SSL 证书出现了问题。
@LucienShui

**Comment by LucienShui** [comment]
感谢提醒，被百度云加速给坑了，切到 cloudflare 了。Orz

**Comment by N-628** [comment]
SSL 证书好像还是有问题。
---
@LucienShui
