### ISSUE TITLE
[自学路漫漫]

### ISSUE THREAD

**Issue by N-628** [saveweb/doing#175]
### ID: 218

https://blog.fxcdev.com

#### 出现了什么问题：

打开网站显示的是Nginx的欢迎页面，非博客页面。

---

@T-Oner

**Comment by T-Oner** [comment]
@1C8199D3C9F1 服务器被挖矿了，正在重新建站

**Comment by cronfox** [comment]
> @1C8199D3C9F1 服务器被挖矿了，正在重新建站

允悲，建议Hexo/Hugo/Vuepress之类的静态博客生成器方案。

并参考目前的最佳实践来解决安全问题

**Comment by T-Oner** [comment]
已经修复

**Comment by N-628** [comment]
好的。
Feed 链接已更新。
