### ISSUE TITLE
[梦墨's Blog]

### ISSUE THREAD

**Issue by 1c8199d3c9f1** [saveweb/doing#176]
### ID: 907

https://idream.ink/

#### 出现了什么问题：

打开博客网站，显示「提示：该域名已过期，不能正常访问，续费后可恢复使用。」

---

@Dreamink0

**Comment by Dreamink0** [comment]
域名已到期，犹豫要不要放弃续费以及放弃博客。

**Comment by Dreamink0** [comment]
更换域名为dreamo.ink，
博客正在筹备重建。

**Comment by Dreamink0** [comment]
博客已重建

**Comment by yzqzss** [comment]
volfclub/travellings 已在 https://github.com/volfclub/travellings/issues/440 留言；
https://linsip.cn/links/ 已发提醒更新的评论；
https://blog.isteed.cc/ Telegram已发私聊提醒；
https://www.addesp.com/links 已发提醒更新的评论；
https://yzyyz.top/friends/ 已发提醒更新的评论；
http://www.telihai.com/archives/9071/ 已发提醒更新的评论；
https://blog.devyi.com/links.html 已发提醒更新的评论；
https://musenxi.com/Add-URL.html 已发提醒更新的评论；
https://www.gymxbl.com/links/ 已发提醒更新的评论；
https://blog.zhangda.xyz/talktome/ 已发提醒更新的评论；
https://www.kiwiape.cn/links.html 已发提醒更新的评论。

```
友链更新提醒：
Name: 梦墨's Blog
URL: https://idream.ink/ -> https://blog.dreamo.ink/
```

使用名称：saveweb
使用邮箱：saveweb@othing.xyz

**Comment by yzqzss** [comment]
BOX 已更新。

**Comment by yzqzss** [comment]
@Dreamink0 ，还有，你以前的老文章会迁移到新博客吗？一些质量还不错啊。

**Comment by Dreamink0** [comment]
老的文章由于资料丢失无法恢复，不过会找个时间进行重置。

**Comment by Dreamink0** [comment]
> volfclub/travellings 已在 [volfclub/travellings#440](https://github.com/volfclub/travellings/issues/440) 留言； https://linsip.cn/links/ 已发提醒更新的评论； https://blog.isteed.cc/ Telegram已发私聊提醒； https://www.addesp.com/links 已发提醒更新的评论； https://yzyyz.top/friends/ 已发提醒更新的评论； http://www.telihai.com/archives/9071/ 已发提醒更新的评论； https://blog.devyi.com/links.html 已发提醒更新的评论； https://musenxi.com/Add-URL.html 已发提醒更新的评论； https://www.gymxbl.com/links/ 已发提醒更新的评论； https://blog.zhangda.xyz/talktome/ 已发提醒更新的评论； https://www.kiwiape.cn/links.html 已发提醒更新的评论。
> 
> 评论内容：
> 
> ```
> 友链更新提醒：
> Name: 梦墨's Blog
> URL: https://idream.ink/ -> https://blog.dreamo.ink/
> ```
> 
> 使用名称：saveweb 使用邮箱：[saveweb@othing.xyz](mailto:saveweb@othing.xyz)

已将上述博客添加至友链。

**Comment by yzqzss** [comment]
> 老的文章由于资料丢失无法恢复，不过会找个时间进行重制。

已将 @1c8199d3c9f1 备份的 repo 存档发于您。
