### ISSUE TITLE
[一大加贝]

### ISSUE THREAD

**Issue by 1C8199D3C9F1** [saveweb/doing#179]
### ID: 410

https://blog.yidajiabei.xyz/

#### 出现了什么问题：

博客链接已经换为 https://www.yidajiabei.xyz/blog/ 。
由于博主更换了静态博客生成工具，RSS地址已经失效。

---
@tianheg

**Comment by tianheg** [comment]
我不知道还会有人在意我的博客，十分感谢！

我使用了 Emacs 下的 Org-mode 生成静态博客，去年 11 月份迁移的时候没弄明白怎么设置 RSS。今天会研究一下怎么添加 RSS。如果添加成功，会在 https://github.com/timqian/chinese-independent-blogs 更新

**Comment by yzqzss** [comment]
@tianheg 好的！

**Comment by tianheg** [comment]
https://github.com/timqian/chinese-independent-blogs/pull/923 终于可以了

**Comment by yzqzss** [comment]
@tianheg RSS中输出的条目实在太多了。建议限制一下输出数量（10～20），并开启全文输出（如果可以的话）。

**Comment by tianheg** [comment]
好的











一大加贝
***@***.***

**Comment by tianheg** [comment]
输出数量已经设置为20
