### ISSUE TITLE
[Khan's Lab]

### ISSUE THREAD

**Issue by lijiakaijun** [saveweb/doing#18]
ID:357
https://yiti.ml
显示响应时间过长

**Comment by yzqzss** [comment]
robin4han.github.io 也404了。
已发邮件询问。

**Comment by gledos** [comment]
胸毛齐腰与 Khan's Lab，对照过两个博客的文章，是基本相同的，似乎博主将原博客做了拆分，一边是技术，另一边是翻译

+ [胸毛齐腰](https://dearxs.github.io/)
+ [大力译文](https://dearbojack.github.io/)

**Comment by yzqzss** [comment]
> 
> 
> 胸毛齐腰与 Khan's Lab，对照过两个博客的文章，是基本相同的，似乎博主将原博客做了拆分，一边是技术，另一边是翻译
> 
>     * [胸毛齐腰](https://dearxs.github.io/)
> 
>     * [大力译文](https://dearbojack.github.io/)

已将原博客移入墓场，并订阅两个新博客：
> ID:925 https://dearxs.github.io/index.xml
> ID:926 https://dearbojack.github.io/index.xml
