### ISSUE TITLE
[求闻 — 中国大陆维基人]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#181]
### ID:977
https://qiuwen.wmcug.org.cn/
#### 出现了什么问题：
CDN回源失败，502。

因此前的「[2021年维基媒体基金会针对中文维基百科的行动 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/2021%E5%B9%B4%E7%BB%B4%E5%9F%BA%E5%AA%92%E4%BD%93%E5%9F%BA%E9%87%91%E4%BC%9A%E9%92%88%E5%AF%B9%E4%B8%AD%E6%96%87%E7%BB%B4%E5%9F%BA%E7%99%BE%E7%A7%91%E7%9A%84%E8%A1%8C%E5%8A%A8)」，该组织可能已解散。

---

Update: 没解散，还和字节跳动一块儿搞了一个「求闻百科」。

**Comment by Mabbs** [comment]
刚刚试着访问了一下可以正常访问。

**Comment by 1C8199D3C9F1** [comment]
网站打开显示Apache2 Ubuntu Default Page。

**Comment by yzqzss** [comment]
已 Telegram 联系，等待回复。

**Comment by yzqzss** [comment]
不处理，移至“墓地轨道”分类。
