### ISSUE TITLE
[Bboysoul's Blog]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#188]
### ID:760
https://www.bboy.app/
#### 出现了什么问题：
Cloudflare 回源失败，522。

![图片](https://user-images.githubusercontent.com/30341059/154794621-787d5b2c-9712-4b54-afc0-5b5838024906.png)

---
@bboysoulcn

**Comment by bboysoulcn** [comment]
> ### ID:760
> https://www.bboy.app/
> 
> #### 出现了什么问题：
> Cloudflare 回源失败，522。
> 
> ![图片](https://user-images.githubusercontent.com/30341059/154794621-787d5b2c-9712-4b54-afc0-5b5838024906.png)
> 
> @bboysoulcn

博客放在家里的，周末貌似断了下网，太忙了没怎么关注

**Comment by cronfox** [comment]
什么桌下可用区
建议搞自动检测在线状态的工程(

**Comment by bboysoulcn** [comment]
> 什么桌下可用区

有检测的，只是周末太忙了懒得操作了

**Comment by yzqzss** [comment]
> Error 502 Bad gateway
又炸了。

**Comment by bboysoulcn** [comment]
感谢，家里的nas炸了，新nas马上到，过几天恢复
