### ISSUE TITLE
[无绘无会] -> [Village]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#189]
### ID:4
https://blog.moennar.cn/
#### 出现了什么问题：
SSL证书过期。

p.s. :~博客还没有更新吗？~

---
@MliKiowa

前倾提要：#61

**Comment by G-256** [comment]
现在变成未备案状态了。

```
网站暂时无法访问
该网站未根据工信部相关法律规则进行备案，
在中国大陆境内提供服务的网站都应依法进行 ICP 备案和公安备案
```

**Comment by MliKiowa** [comment]
之前由于是高中学业(现在毕业了) 博客长时间没搭理 备案后(主域名一直未建设 其实有通知我也改了 但是高中很难拿到手机) 导致咱备案掉了 数据的话咱没备份 (如果我还会写博客的话 我一定不备案了

**Comment by MliKiowa** [comment]
> > 之前由于是高中学业(现在毕业了) 博客长时间没搭理 备案后(主域名一直未建设 其实有通知我也改了 但是高中很难拿到手机) 导致咱备案掉了 数据的话咱没备份 (如果我还会写博客的话 我一定不备案了
> 
> https://box.othing.xyz/i/?get=f_4 这里面的备份你要吗？可以把 MarkDown 发给你。

可以的 邮箱在这里 也可以QQ联系
Mail: 1627126029@qq.com (nineto0@qq.com)

**Comment by MliKiowa** [comment]
其实这个虽然没备份但是当时同步了腾讯云那边平台

**Comment by yzqzss** [comment]
> 可以的 邮箱在这里 也可以QQ联系

用 saveweb@othing.xyz 这个邮箱把备份发给你了，注意查收。

**Comment by MliKiowa** [comment]
那这个issue可以close了吧

**Comment by yzqzss** [comment]
新域名：<https://nanaeo.cn/>

---
有兴趣加个RSS吗？

**Comment by MliKiowa** [comment]
正在加入呢 不过不知道什么hexo插件好用

**Comment by MliKiowa** [comment]
> 新域名：https://nanaeo.cn/
> 
> 有兴趣加个RSS吗？

https://nanaeo.cn/rss.xml
https://nanaeo.cn/feed.json
https://nanaeo.cn/atom.xml

**Comment by yzqzss** [comment]
已更新名称：「Village」
Feed：https://nanaeo.cn/atom.xml
