### ISSUE TITLE
[David前端技术分享]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#19]
ID:50
https://daweilv.com
这个是2022-06-11(UTC)才过期
但是box.othing.xyz上的文章最后获取时间是19年
尝试访问时提示“此网站无法提供安全连接”

**Comment by lijiajunljj** [comment]
https://github.com/daweilv/daweilv.github.io/issues/1#issuecomment-861231801
回复

**Comment by lijiajunljj** [comment]
更新下
网站：https://lvdawei.com/
没有订阅链接
有对应上游（https://github.com/timqian/chinese-independent-blogs）

**Comment by yzqzss** [comment]
虽然主站没有，但github page有feed链接。
https://daweilv.github.io/atom.xml
还好，feed的内链是指向的主站。

@daweilv 
希望博主您能把feed源也一起push到主站。
