### ISSUE TITLE
[纬八路生活随笔集]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#192]
### ID:1103
http://www.weibalu.com
#### 出现了什么问题：
似乎变成垃圾站了。
![图片](https://user-images.githubusercontent.com/30341059/156339606-3b53c11b-4685-489c-bfd3-4aab9a1c90b9.png)

**Comment by 1C8199D3C9F1** [comment]
根据博主的公众号文章来源，博主已在2022-02-22日售出了自己的「维八路」博客。
[来源](https://mp.weixin.qq.com/s/Y1SVopooxLOAUlEwVeqtiQ)

博主于2022-02-27发表了一篇文章说自己申请了新的域名「如是乎」，现在在备案当中，博主在文章说备案成功他的博客还会继续下去。
[来源](https://mp.weixin.qq.com/s/2UxDkgiAPcKvna0Xbva5_g)

**Comment by linlinzzo** [comment]
> 根据博主的公众号文章来源，博主已在2022-02-22日售出了自己的「维八路」博客。 [来源](https://mp.weixin.qq.com/s/Y1SVopooxLOAUlEwVeqtiQ)
> 
> 博主于2022-02-27发表了一篇文章说自己申请了新的域名「如是乎」，现在在备案当中，博主在文章说备案成功他的博客还会继续下去。 [来源](https://mp.weixin.qq.com/s/2UxDkgiAPcKvna0Xbva5_g)

可以提供一下【如是乎】的博客地址，谢谢。

**Comment by G-256** [comment]
@linlinzzo rushihu.com

现在仍在备案阶段，暂时无法访问。

https://mp.weixin.qq.com/s?__biz=MzIyNzEzMTcwOQ==&mid=2648816620&idx=1&sn=85379a63a752a8a11382d5c6932d450a&chksm=f070f3bec7077aa831f1377ea7bc78f621e61fd5a6f9a7a71af679721d854297a9ea397d04df

**Comment by yzqzss** [comment]
@linlinzzo 其新博客已上线。

Site: https://rushihu.com/
Feed: https://rushihu.com/feed

**Comment by cronfox** [comment]
> https://github.com/saveweb/doing/issues/192#issuecomment-1129491700
NOT HTTPS.
![image](https://user-images.githubusercontent.com/86996742/168943124-a6ecfd34-de7b-461b-b342-c51d724221f4.png)

**Comment by linlinzzo** [comment]
> @linlinzzo 其新博客已上线。
> 
> Site: http://rushihu.com/ Feed: http://rushihu.com/feed

已添加，序号1613。

**Comment by yzqzss** [comment]
BOX 已订阅新博客，ID: 1524 。
旧博客已移入「墓地轨道」。

**Comment by yzqzss** [comment]
十年之约id: 608
已更新链接。
