### ISSUE TITLE
[Grayson's blog]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#194]
### ID:291
http://blog.grayson.org.cn
#### 出现了什么问题：
访问无响应，长时间等待后，nginx报超时错误。
```
504 Gateway Time-out
nginx/1.18.0 (Ubuntu)
```
另，博客最后更新于2019年5月。本次可能是关站。

---
@graysonchen

**Comment by 1C8199D3C9F1** [comment]
HTTP已无问题。HTTPS访问有错误。

**Comment by graysonchen** [comment]
谢谢，ssl证书将尽快更新。

**Comment by yzqzss** [comment]
> 谢谢，访问正常啊。ssl证书将尽快更新。

询问一下， http://growcn.com/ 博客会迁移到这个域名吗？

**Comment by graysonchen** [comment]
http://blog.grayson.org.cn 这个是在growcn.com设置了一个别名域名。所以说不会迁移。

**Comment by yzqzss** [comment]
好的。
