### ISSUE TITLE
[DHTalk's Blog]

### ISSUE THREAD

**Issue by N-628** [saveweb/doing#202]
### ID: 345

https://zhangdinghao.cn/

#### 出现了什么问题：

The requested URL '/' was not found on this server. 

---

@CalvinCheungCoder

**Comment by yzqzss** [comment]
似乎国内IP无法访问此网站，你们试试挂代理看能不能访问？（第一次见到中文博客反向屏蔽国内IP的情况）

**Comment by 1c8199d3c9f1** [comment]
@yzqzss 我开代理可以正常访问，拿国内IP会连接已重置。

**Comment by gledos** [comment]
[17ce](https://web.archive.org/web/20220314020713/http://17ce.com/site/http/20220314_4a8daec0a33b11eca8ff613adab63e9c:1.html) 有 75% 左右的节点无法正常使用。

![圖片](https://user-images.githubusercontent.com/23720620/158092665-616a692a-379a-4174-bf77-bef4a41e9563.png)

**Comment by yzqzss** [comment]
找到可能的原因了，这个域名疑似同时使用了 cloudflare、digitalocean、netlify.app、Github.io 等多种静态Pages服务。不同区域可能会解析到不同服务的IP上。而我这边被解析到了 Github.io ，但是由于他的域名是 .cn ，所以我的代理工具给他走了直连——我这边是直连不上 Github.io 的。

**Comment by 1c8199d3c9f1** [comment]
@yzqzss 我使用移动卡使用移动数据解析的IP地址：

172.67.137.10

**Comment by 1c8199d3c9f1** [comment]
@yzqzss 我使用联通卡的移动数据则解析到该 IP 地址：54.255.56.197
