### ISSUE TITLE
[小熊写字的地方]

### ISSUE THREAD

**Issue by 1c8199d3c9f1** [saveweb/doing#207]
### ID: 304

https://blog.skrskrskrskr.com/

#### 出现了什么问题：

域名解析超时。

![img_MrwT91g0](https://user-images.githubusercontent.com/94344766/158023958-6180e2df-2418-4dc4-9cae-4aa96a429f98.png)

---

@FrankXiong

**Comment by FrankXiong** [comment]
之前用的coding的静态托管服务下线了，现在迁到自己的服务器上了，已经恢复访问

**Comment by Mabbs** [comment]
> 之前用的coding的静态托管服务下线了，现在迁到自己的服务器上了，已经恢复访问

看起来变成了
<wave.skrskrskrskr.com>
这个地址，而且不是博客
