### ISSUE TITLE
[小简博客]

### ISSUE THREAD

**Issue by N-628** [saveweb/doing#208]
### ID: 950

https://blog.janyork.com

#### 出现了什么问题：

没有解析。

---

@JanYork

**Comment by N-628** [comment]
根据搜索引擎搜索，博主已在前四天使用博客园来写博客。

https://www.cnblogs.com/JanYork/

**Comment by N-628** [comment]
博客新地址：

https://blog.ideaopen.cn/

**Comment by yzqzss** [comment]
据：[重构说明 - 小简博客](https://blog.ideaopen.cn/index.php/archives/7/)

>我博客重构了，没有剩下一篇文章！
>
>没法，数据库不小心被我玩没了，加上没时间修复博客，干脆重构吧！

已QQ联系博主。

**Comment by yzqzss** [comment]
博主说事故发生后，文章数据回滚了，但是图片都找不回来了，所以以前的文章“干脆就不要了”。

**Comment by yzqzss** [comment]
BOX已更新Feed：https://blog.ideaopen.cn/index.php/feed/
