### ISSUE TITLE
[山月]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#213]
### ID:1182
https://sanguok.com/
#### 出现了什么问题：
数据库出错`建立資料庫連線時發生錯誤`。

---
@Guanchishan

**Comment by Guanchishan** [comment]
谢谢您提醒，原因目前还在排查。

yzqzss ***@***.***> 于2022年3月29日周二 13:06写道：

**Comment by Guanchishan** [comment]
已恢复
