### ISSUE TITLE
[Power's Wiki Blog]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#215]
### ID:803
https://wiki-power.com/blog/atom.xml
#### 出现了什么问题：
博主更改网站结构，导致 RSS(atom.xml) 404。

---
@linyuxuanlin ，博主您好，请问您有重新支持RSS的计划吗？

**Comment by cronfox** [comment]
我先去挖掘一下 看看有啥替补RSS

**Comment by linyuxuanlin** [comment]
这个项目还不错诶，晚点我也详细了解一下。
我的站点是基于 Docusaurus 框架的，前几天刚把博客的功能关了，把内容全整合到 docs 的形式下了，但Docusaurus 的 docs 形式好像还没有官方支持 RSS 的功能，所以暂时还没有解决方法。
如果之后有解决方法我会来这里回复。

**Comment by yzqzss** [comment]
> 如果之后有解决方法我会来这里回复。

好的！

**Comment by linyuxuanlin** [comment]
已经恢复博客与 RSS 订阅功能，订阅地址还是原来的 <https://wiki-power.com/blog/rss.xml> 。我自己试了能打开，如果有问题请留言~

**Comment by yzqzss** [comment]
嗯，试了，是正常的。Thanks！

**Comment by linyuxuanlin** [comment]
Hello @yzqzss ，我的博客由于更换了框架，导致 RSS 订阅地址发生变更，但是我不知道在哪里 pull request。
如果方便的话，可以帮我更新一下吗？

原地址（已失效）： https://wiki-power.com/blog/rss.xml
新地址（首选）：https://wiki-power.com/feed_rss_updated.xml
新地址（备用）：https://wiki-power.com/feed_rss_created.xml

Thanks so much~
