### ISSUE TITLE
[u3coding] [u3shadow的博客]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#217]
### ID:754
http://www.u3coding.com/
#### 出现了什么问题：
域名过期。

---
@u3shadow ，请问您的博客是换新域名了吗？

**Comment by ghost** [comment]
Blog 地址已更换为 https://u3blog.xyz/
但是没有发现订阅地址，可能失效了。

**Comment by gledos** [comment]
已找到订阅地址：<https://u3blog.xyz/feed.php>

看起来有 10 篇。

**Comment by ghost** [comment]
BOX 上的 Blog 地址与订阅地址已更新。博客名称已更改为「u3blog」。

**Comment by u3shadow** [comment]
之前的博客因为黑客攻击，重新部署换了新地址，谢谢各位

**Comment by ghost** [comment]
上游已合并。
