### ISSUE TITLE
[左胡](胡子博客)

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#221]
#### 出现了什么问题：

更换域名:[博客搬家 – 胡子博客](https://huzizi.com/blog-move/)。
huzizi.com -> zuo.hu

B0X已更新。

- https://github.com/timqian/chinese-independent-blogs/pull/1037 已更新。
- @zh-blogs/list-team 请注意更新。

相关:#131

**Comment by linlinzzo** [comment]
中文博客列表导航 id 1221，已进行修改。

**Comment by linlinzzo** [comment]
艾特小组好像没用······特别是其它的组织。

**Comment by yzqzss** [comment]
idx 1221
又换域名了：
https://hugobingo.com/
https://hugobingo.com/index.xml

**Comment by linlinzzo** [comment]
> idx 1221 又换域名了： https://hugobingo.com/ https://hugobingo.com/index.xml

idx 1220 信息已修改。

**Comment by yzqzss** [comment]
> idx 1220 信息已修改。

idx 编号变了？

**Comment by linlinzzo** [comment]
> idx 编号变了？

后台是 1220，具体原因不知道。
