### ISSUE TITLE
[Lihaoya 的技术博客]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#227]
### ID:819
https://blog.lihaoya.com/
#### 出现了什么问题：
域名无法解析。疑似是 <https://typetype.io/> 关停引起的。

---
@blackstorm

**Comment by yzqzss** [comment]
> 域名无法解析。疑似是 https://typetype.io/ 关停引起的。

据其[个人主页](https://www.lihaoya.com/)， typetype.io 就是他自己开发的博客托管平台。

---
目前博客已更换(?)为 WordPress 并恢复访问，以前的文章清空了，

**Comment by blackstorm** [comment]
@yzqzss Sorry for the late reply, yes because typetype closed, my blog was not accessible at that time.
