### ISSUE TITLE
[EdenJohnson瞎写小屋]

### ISSUE THREAD

**Issue by Eden7Ba23** [saveweb/doing#228]
#### 出现了什么问题：
个人决定关站。

---

https://github.com/Eden7Ba23/BlogBackup/

如可，请不要 Archive 挂了 hide: true 的文章。同时，这些文章同样没有价值，请不要 Archive。

 > https://blog.edenjohnson.cyou/2021/07/17/YOU-WIN/
 >
 > https://blog.edenjohnson.cyou/2021/06/06/the-article-with-no-more-updates-or-waiting-to-update/
 > 
 > https://blog.edenjohnson.cyou/2020/06/24/the-true-first-post/
 > 
 > https://blog.edenjohnson.cyou/2020/06/24/hello-world/

请在完成后即通知我，我会立刻注销账号。

感谢。

**Comment by wrap-zone** [comment]
@Eden7Ba23 已通过私信联系，等待回复。

**Comment by wrap-zone** [comment]
@wrap-zone 已经 archive 完毕。

对 web.archive.org 没有的文章，进行了补充。（不包括提到的低质量的文章和含有 hide 标签的文章）

通过我的检查，archive.today 没有全站的存档，已经做了存档。（同样做了排除）

仓库已经使用了 clone 来保存。
