### ISSUE TITLE
[GrassBlock's Blog]

### ISSUE THREAD

**Issue by GrassBlock1** [saveweb/doing#229]
### ID: 908
https://blog.imgb.space
#### 出现了什么问题：
好久没打理，加上一直在实验室折腾，即将重开博客 (https://blog.imgb.space 即标题所指的站点名称) ，并换用Jekyll作为网站引擎。 希望能够尽快在此存档。

备注：
尽量备份所有内容，并尽快将备份结果告知。

**Comment by kuohuanhuan** [comment]
Jekyll 草

**Comment by gledos** [comment]
嗯，存档已开始。

**Comment by yzqzss** [comment]
接单了。

**Comment by GrassBlock1** [comment]
> Jekyll 草

🌚

**Comment by yzqzss** [comment]
@gledos @yzqzss @wrap-zone 
已完成备份，并发给博主。
Internet Archive 和 Archive Today 均已存档。（除了酷安的外链图片反爬导致无法存档，但我们做了本地存档（下载））

**Comment by yzqzss** [comment]
@GrassBlock1 先留着，因为你之后换博客程序。我们这里到时候要更新一下你的博客信息。

**Comment by yzqzss** [comment]
22天过去了，快换博客程序！

**Comment by GrassBlock1** [comment]
> 22天过去了，快换博客程序！

在写作业 马上🕊️

**Comment by yzqzss** [comment]
feed已更新：https://blog.imgb.space/feed.xml

**Comment by GrassBlock1** [comment]
> feed已更新：https://blog.imgb.space/feed.xml

这rss怎么找到的 我自己都没找到（（（（
