### ISSUE TITLE
[束花柳の家]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#238]
### ID:1522
https://www.rmoe.top/2022/07/23/376.html
#### 出现了什么问题：
博客丢失4个月份的数据。

@Sualiu ，我们这里有部分备份，要吗？

**Comment by Sualiu** [comment]
好啊^o^~，真的谢谢你！正为了如何重新写那些文章苦恼呢，忘了好多了。




对了，能问一下，您为什么会有我的部分备份数据嘛？这是什么项目……以前还没有听说过……


非常感谢您的帮助，送上真挚的感谢与祝福。谢谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月25日(周一) 晚上6:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [saveweb/doing] [束花柳の家] (Issue #238)




 
ID:1522
 
https://www.rmoe.top/2022/07/23/376.html
 
出现了什么问题：
 
博客丢失4个月份的数据。
 
@Sualiu ，我们这里有部分备份，要吗？

**Comment by yzqzss** [comment]
嗯，我们正在把备份的html转换成markdown格式，有些小瑕疵，还正在处理。  

> 对了，能问一下，您为什么会有我的部分备份数据嘛？这是什么项目……以前还没有听说过……

这个问题，我们稍后会回复。

**Comment by cronfox** [comment]
> 对了，能问一下，您为什么会有我的部分备份数据嘛？这是什么项目……以前还没有听说过…… 

我们上周测试了一个将我们收录的RSS的文章全部推送到 web.archive.org 的项目

**Comment by yzqzss** [comment]
准确地说，19号的时候，我们用「十年之约」的RSS系统的API，把其RSS系统中所有的文章都做了一次 archive.org 备份。正好覆盖到了您的博客。同时，自19号起，十年之约RSS系统中收到的新文章都会每日推送到 archive.org 存档。

见：<https://t.me/s/blogrsslist/370>

另外，我们刚刚也把您的博客收录到了我们的 saveweb/rss-list 当中，所以分配了一个博客ID号：1522 。

---

简单但不全面地说，本项目（Save The Web Project）是一个为 已关站/将要关站 的 博客/网站 建立存档的纯公益项目。  
有点类似于 [ArchiveTeam](https://wiki.archiveteam.org/) 。

**Comment by yzqzss** [comment]
![image](https://user-images.githubusercontent.com/30341059/180776752-0dd0ad10-df23-4f3f-8c2b-0f7a3e7b4017.png)

@Sualiu 丢的是这些文章吧？你看看还有没有缺的？

**Comment by Sualiu** [comment]
是的，经过一些核对，就是这些，甚至这里面包含了更多。


非常感谢您！否则我又得头疼一段时间了。


若是需要这些数据，我还需要做些什么？谢谢您的付出，非常感谢。

**Comment by yzqzss** [comment]
> 若是需要这些数据，我还需要做些什么？谢谢您的付出，非常感谢。

给 saveweb@othing.xyz 随意发封信，我会在回复里把备份发给你。

**Comment by yzqzss** [comment]
已发邮件。

**Comment by yzqzss** [comment]
已恢复。

**Comment by Sualiu** [comment]
已收到。

**Comment by Sualiu** [comment]
好的，谢谢。
