### ISSUE TITLE
[依米]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#239]
### ID:885
https://www.feed.cc/
#### 出现了什么问题：
打开显示“目前网站正在建设中”。

**Comment by yzqzss** [comment]
已恢复。
之前的文章没有保留。（IA上有）

**Comment by yzqzss** [comment]
@wuxiaocong 博主，冒昧问一下，之前的文章是丢失了，还是因为博客重建所以选择“重新开始”？

**Comment by wuxiaocong** [comment]
东西没丢，不确定还要不要写博客了

**Comment by wuxiaocong** [comment]
> @wuxiaocong 博主，冒昧问一下，之前的文章是丢失了，还是因为博客重建所以选择“重新开始”？

东西没丢，不确定还要不要写博客了
