### ISSUE TITLE
[XiaoHui.com]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#24]
ID:448
网站正常访问，RSS无报错，国际网络环境能访问，但box.othing.xyz只获取到20年的文章
最近一次文章发布是21年04月
订阅链接：https://www.xiaohui.com/rss

**Comment by yzqzss** [comment]
我这边网站打不开，能ping通，但丢包严重。

```
--- xiaohui.com ping 统计 ---
已发送 104 个包， 已接收 10 个包, 90.3846% packet loss, time 104361ms
rtt min/avg/max/mdev = 190.340/194.475/197.469/3.160 ms

```
w3c验证结果：
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.xiaohui.com%2Frss

FreshRSS设置不验证SSL安全性，也没有效果。

**Comment by yzqzss** [comment]
临时处理方案：移动到“RSS不规范”分类。
