### ISSUE TITLE
[薄荷的猫草]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#242]
### ID: 1525
url: https://bohecat.com/
#### 出现了什么问题：
https://bohecat.com/ -> mou.ge
301 重定向后的新域名`mou.ge`无法访问。原域名的解析 ip 可直接访问： <http://1.15.71.117>。
应该是网站迁移还没做完。

**Comment by cronfox** [comment]
我目前没有问题
![image](https://user-images.githubusercontent.com/86996742/187072666-3a2b2cc2-3875-4b95-bca7-d8b6549c827a.png)

```
$ dig @1.1.1.1 mou.ge

; <<>> DiG 9.16.1-Ubuntu <<>> @1.1.1.1 mou.ge
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9495
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;mou.ge.                                IN      A

;; ANSWER SECTION:
mou.ge.                 591     IN      A       103.133.178.202

;; Query time: 184 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Sun Aug 28 19:47:57 CST 2022
;; MSG SIZE  rcvd: 51
```

**Comment by cronfox** [comment]
看起来需要等DNS TTL...

**Comment by yzqzss** [comment]
![image](https://user-images.githubusercontent.com/30341059/187073519-f5012167-0f9e-4c7f-a71e-b469b1d58744.png)
![image](https://user-images.githubusercontent.com/30341059/187073535-7500f581-0630-4261-b74c-cdffa9c722e1.png)

已查明，是服务器那边屏蔽了部分地区/网络。就是这个屏蔽规则有点迷惑……

**Comment by cronfox** [comment]
我怀疑是用了过期规则(
