### ISSUE TITLE
[Atlas' Blog]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#243]
### ID: 1245
url: https://atlasoin.xyz/atom.xml
#### 出现了什么问题：

`hexo-generator-feed` 在 <https://github.com/AtlasQuan/AtlasQuan.github.io/commit/f9a5fc241298c1d7a5441361219162c91d222b41> 中被移除，导致 feed 404。

---
@AtlasQuan

**Comment by Atlasoin** [comment]
Thanks for notifying me! It has been fixed.
