### ISSUE TITLE
[JalenChuh] -> [Jalen]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#245]
### ID: 425
url: https://blog.jalenchuh.cn -> https://jalenz.cn/
#### 出现了什么问题：
域名变更，内容清空（历史文章保留在[仓库](https://github.com/jalenchuh/blog)记录中）。

BOX已更新，仅记录。

**Comment by yzqzss** [comment]
@linlinzzo

https://github.com/travellings-link/travellings:
| 94 | LOST | JalenChuh | ~~https://blog.jalenchuh.cn~~ |

注意修改。

---
另，zh-blogs 中没有收录，无需检查。

**Comment by linlinzzo** [comment]
已通知组内的人员处理。

**Comment by essesoul** [comment]
![image](https://user-images.githubusercontent.com/58624474/187475654-dbc9d9e5-808a-4d0e-98b3-909b07c927d1.png)
未在网站https://jalenz.cn 上找到开往的文字、徽标或链接

**Comment by yzqzss** [comment]
> 未在网站 <https://jalenz.cn> 上找到开往的文字、徽标或链接

那就把状态改成 `QUIT` ？

---
CC: @jalenchuh

**Comment by linlinzzo** [comment]
> 那就把状态改成 `QUIT` ？

已在 PR 中修改，等待合并。
