### ISSUE TITLE
[SC's 神奇的JavaWeb]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#249]
### ID: 1478
url: https://shicheng.cool/
#### 出现了什么问题：
无法访问。（能ping通，证书也正常(?)）

---
@PrintSC

**Comment by PrintSC** [comment]
感谢您的指出，现在已经恢复了。
再次感谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "saveweb/doing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月28日(星期天) 晚上11:58
***@***.***&gt;;
抄送:&nbsp;"The Snow ***@***.******@***.***&gt;;
主题:&nbsp;[saveweb/doing] [SC's 神奇的JavaWeb] (Issue #249)





 
ID: 1478
 
url: https://shicheng.cool/
 
出现了什么问题：
 
无法访问。（能ping通，证书也正常(?)）
 
 
@PrintSC

**Comment by yzqzss** [comment]
好的！
