### ISSUE TITLE
[Zeove'blog]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#25]
ID:107
https://zeove.com
访问时显示zeove.com 意外终止了连接。

**Comment by yzqzss** [comment]
@zeove

**Comment by yzqzss** [comment]
已发Twitter询问：

<blockquote class="twitter-tweet"><p lang="zh" dir="ltr">您好，您的博客(<a href="https://t.co/uwsBqh3bwY">https://t.co/uwsBqh3bwY</a>)已经很长一段时间都无法访问了。请问您博客还打算继续开下去吗？还是关站？<a href="https://t.co/LYNKseSNmw">https://t.co/LYNKseSNmw</a></p>&mdash; yzqzss|一座桥在水上 (@yzqzss_me) <a href="https://twitter.com/yzqzss_me/status/1423499422252425220?ref_src=twsrc%5Etfw">August 6, 2021</a></blockquote>

**Comment by yzqzss** [comment]
> 已发Twitter询问：

最近该博主的 Twitter 活动频繁，但我依然没有收到其回复，看情况这位博主继续开博客的意愿应该不强烈。
进入 Save The Web Project 程序！

**Comment by yzqzss** [comment]
主题已调整。

**Comment by yzqzss** [comment]
box 分类已移动到墓场。

**Comment by yzqzss** [comment]
已pr上游，移除收录。
