### ISSUE TITLE
[Yuexun`s Blog]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#258]
### ID: 213
url: https://yuexunjiang.me/
#### 出现了什么问题：
Vercel: 404: NOT_FOUND

---
@ahonn

**Comment by ghost** [comment]
Blog 地址更换为 https://www.yuexun.me/

RSS 地址：https://www.yuexun.me/feed.xml

**Comment by ghost** [comment]
BOX 上的 Blog 地址与 RSS 地址已更新。
