### ISSUE TITLE
[Eulerian Moe]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#266]
### ID: 1214
url: https://eulerian.xyz/
#### 出现了什么问题：
域名过期： `autoRenewPeriod（自动续费宽限期）`

info:
> repo: https://github.com/EulerianMoe/eulerianmoe.github.io

---
@EulerianMoe

**Comment by yzqzss** [comment]
已TG联系。

**Comment by ghost** [comment]
博主已经删除 CNAME，可以确定 Blog 地址已经更换为 https://eulerianmoe.github.io/

**Comment by ghost** [comment]
BOX 地址已更新。
