### ISSUE TITLE
[iNote]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#268]
### ID: 290
url: https://inote.xyz/rss/
#### 出现了什么问题：
其 RSS 的 `<guid>` 字段似乎是每次构建时随机生成的，导致多篇文章重复N次。问题似乎已存在数月以上(?)。
见：<https://box.othing.xyz/i/?get=f_290>

BOX 已暂停其更新。

---
#134

---
@xiyizhou

**Comment by ghost** [comment]
rss 已修复，可正常更新了
