### ISSUE TITLE
[乱象，印迹]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#27]
ID:471
http://www.luanxiang.org/blog
可能是服务器ip变更或过期，目前网站不是这个内容
没有获取到文章

**Comment by yzqzss** [comment]
> 
> 
> 已pr上游: [RSS-Renaissance/awesome-blogCN-feeds#12](https://github.com/RSS-Renaissance/awesome-blogCN-feeds/pull/12)

https://github.com/RSS-Renaissance/awesome-blogCN-feeds 大概率是停止维护了，最后的commit在2020年3月。项目所有者：https://github.com/xianmin 也多月无任何活动。

**Comment by yzqzss** [comment]
放弃PR上游。
