### ISSUE TITLE
[informal]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#275]
### ID: 
url: http://www.informal.top/index.php/feed/
#### 出现了什么问题：

从 Typecho 切换为静态博客，RSS暂缺。

> 博客从 Typecho 迁移到了 github 上，域名不变。
> 
> 搭建的 Typecho 博客到期了，服务器续费一个月80，域名续费一年29，服务器杀熟太狠了，所以只续了域名。
> 
> 无奈把迁移到了 github 上，今天搞了一天才搞定。挑主题的时候总觉得别人的主题太花哨，想找一个极极极简的，没找到，于是就自己参考各种教程搭建了一个极简风格的。可能有点丑吧，但我的极简的目的达到了。
> 
> Typecho 导出功能也有点麻烦，本来别人写好的有脚本可以导出的，但服务器上python环境还少库，搞起来很麻烦。于是自己写了个[脚本](https://gist.github.com/wa008/7e81528e8831fb0caccd41c3e4ff29ea)解析的 Typecho 备份dat文件，也花了点时间。
> 
> html 0基础，有些内容一边查一边试，就比较花时间，反正弄出来了一个我觉得没啥大问题的版本，先跑一段时间看看吧
> 
> 还有一些问题没解决，比如加评论很麻烦、RSS订阅还没搞、github page 公式解析需要接住外部服务、访问量统计也需要外部服务。毕竟不是自己的服务器，也没办法。github page 能提供这个级别的服务已经很不错了，特别是 action 的功能，能自动构建，速度也挺快的，感觉很棒。
> 
> 去年写了31篇文章，感觉还不错，域名续费了3年，github page 短期也不会倒闭，这个方案起码能保底至少跑3年了。
> 
> ——「[特殊的日子](http://informal.top/2022/11/12/move-typecho-to-github-pages.html)」

---
@wa008

Note: 此 issue 保持长期开放。

**Comment by yzqzss** [comment]
已暂时移动到“不提供RSS”分类。

**Comment by wa008** [comment]
> 已暂时移动到“不提供RSS”分类。

重新添加了RSS订阅链接：http://informal.top/feed.xml
移回去需要我来操作嘛？

**Comment by yzqzss** [comment]
@wa008 您好，不需要的，稍等一会儿即可。

**Comment by cronfox** [comment]
resolved.
close issues.
