### ISSUE TITLE
[Airing 的小屋]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#279]
### ID: 1441
url: <https://me.ursb.me/>
#### 出现了什么问题：
SSL 证书过期(20221126)。

---
@airingursb

**Comment by yzqzss** [comment]
Telegram PM.

**Comment by airingursb** [comment]
通知很及时哈，证书 DDL 日期提醒设置错了，11月底才更新

**Comment by yzqzss** [comment]
> 通知很及时哈，证书 DDL 日期提醒设置错了，11月底才更新

才发现，你这域名不错。xD
