### ISSUE TITLE
[前端社区] / [前端迷]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#28]
ID:426  / 262
https://58fe.com / https://ru23.com/?fr=cib
都是同一个人，虽然是不同网站
已经找到github账户，准备联系

**Comment by yzqzss** [comment]
看来这个项目已经被放弃了。而且看起来完成度也特别低。直接移除其收录吧，不需要我们去 Save 它。

**Comment by yzqzss** [comment]
box 已彻底移除这两个网站。
