### ISSUE TITLE
[提莫酱のBlog]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#283]
### ID: 1266
url: <https://www.timochan.cn/>
#### 出现了什么问题：
RSS (<https://www.timochan.cn/feed>) ，似乎部分网络/UA下，RSS 链接会 403 ，导致RSS无法订阅。可能有防火墙，具体没测试。  
（比如 W3 的验证器就[被 403 了](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.timochan.cn%2Ffeed)）

---
@ttimochan

**Comment by yzqzss** [comment]
Telegram PM.

**Comment by ttimochan** [comment]
从网站的受众以及自身防护考虑，我选择了屏蔽国外的 IP，自然会导致国外的用户访问异常;近期没有观测到攻击，将会考虑关闭，感谢提醒

**Comment by ttimochan** [comment]
Done
