### ISSUE TITLE
[混沌周刊]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#284]
### ID: 1213
url: https://weekly.love/
#### 出现了什么问题：
WordPress 数据库错误 `Error establishing a database connection`

**Comment by yzqzss** [comment]
现在变成了 Nginx HTTP 504：`504 Gateway Time-out` （需要等几十秒）

[Twitter commented](https://twitter.com/yzqzss_me/status/1597974033844563969).

**Comment by Mabbs** [comment]
看起来已经恢复了
