### ISSUE TITLE
[251's Blog.]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#286]
### ID: 552
url: https://blog.251.sh/
#### 出现了什么问题：
<https://blog.251.sh/> CNAME递归两层空DNS解析。  
<https://251.sh/> Cloudflare 报错： `Error 1016 :Origin DNS error`

---
@misaka00251

**Comment by misaka00251** [comment]
感谢反馈，看起来是因为 CDN down 了。

**Comment by misaka00251** [comment]
已经恢复

**Comment by cronfox** [comment]
fixed
