### ISSUE TITLE
[咲夜の小屋]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#29]
ID:504
https://www.moesakuya.xyz
似乎是主机过期了

**Comment by yzqzss** [comment]
已发QQ好友申请，等待通过。

**Comment by yzqzss** [comment]
![图片](https://user-images.githubusercontent.com/30341059/122635866-ccc7d280-d118-11eb-880a-990aab1392ef.png)

在和博主交流，看看他有没有重建博客的打算。

**Comment by yzqzss** [comment]
![图片](https://user-images.githubusercontent.com/30341059/122663640-b8461180-d1ce-11eb-83ce-7ce54d46623f.png)
![图片](https://user-images.githubusercontent.com/30341059/122663644-c7c55a80-d1ce-11eb-9de9-edf884b65911.png)

OK，已帮助博主重建网站: https://moesakuya.xyz
box已更新Feed: https://moesakuya.xyz/feed/
