### ISSUE TITLE
[Bllk]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#3]
ID:499
https://803344.xyz
已联系(https://github.com/guugg/Gridea-Theme-Art/issues/1)

**Comment by yzqzss** [comment]
@guugg

**Comment by yzqzss** [comment]
803344.xyz 主域没有 A/CNAME 记录。

访问 https://art.803344.xyz （泛解析ip:120.24.63.194），会因为SNI的问题转到 https://www.cloopro.com/ （同样指向:120.24.63.194） 这个网站上。

两个域名都是通过阿里云万网注册的。大概率是同一人。

----
已在 https://www.cloopro.com/17.html 留言：
![图片](https://user-images.githubusercontent.com/30341059/128460637-ea8e0882-b1e1-4463-a091-e724443cd9c9.png)

**Comment by guugg** [comment]
@yzqzss 抱歉，才看到

**Comment by yzqzss** [comment]
> @yzqzss 抱歉，才看到

https://github.com/guugg/Gridea-Theme-Art/issues/1#issuecomment-894951084

好的。

---

https://box.othing.xyz/i/?get=f_499 已移入墓地。

**Comment by yzqzss** [comment]
@guugg 你github的profile需要更新一下。
![图片](https://user-images.githubusercontent.com/30341059/128983121-fc994e1e-6cd4-4968-aa18-c9e7f4544a13.png)
