### ISSUE TITLE
[四公子的剑]

### ISSUE THREAD

**Issue by lijiakaijun** [saveweb/doing#30]
ID:238
http://blogbo.org
RSS地址出错，疑似不再提供RSS订阅源
见 https://github.com/dahhd/dahhd.github.io

**Comment by thangpai** [comment]
博主網址已換爲www.965.one，但仍無RSS訂閲Link。

**Comment by yzqzss** [comment]
> 博主網址已換爲www.965.one，但仍無RSS訂閲Link。

https://www.965.one/atom.xml 不是一个 Feed 文件。

@dahhd
