### ISSUE TITLE
[沈维燕的个人主页]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#34]
ID:244
https://shen.bioitee.com/
翻到了2个rss
https://shen.bioitee.com/index.xml （错误）
https://shen.bioitee.com/articles/index.xml （错误）

**Comment by yzqzss** [comment]
https://shen.bioitee.com/about/
```
本博客更新历史：

    2021.03.29：
        更新 footer 样式，实现 Copyright 日期自动更新。
        页脚的 footer 可直接通过 config.toml 进行更新。

    2020.03.13：
        把所有博文更换成了蚂蚁金服旗下 语雀平台 的链接，点击博文链接即可跳转至语雀原文进行阅读。
        本博客不再进行博文内容编写与显示，所有博文将在语雀进行编辑和修改。语雀的文章列表会每天更新至本博客。

```

博客全部文章已迁移语雀，此博客的rss已失效，故从box中移除收录(ID:244)
