### ISSUE TITLE
[TonyHe的博客]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#44]
ID:297
https://blog.ouorz.com
rss出错，报错内容见https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblog.ouorz.com%2Ffeed%2F
![image](https://user-images.githubusercontent.com/55282876/122626550-c36d4480-d0dd-11eb-8702-6606b1f2e6a8.png)

**Comment by gledos** [comment]
### 联系方式

[Github 主页](https://github.com/HelipengTony)含有多个联系方式

**Comment by lijiajunljj** [comment]
> ### 联系方式
> [Github 主页](https://github.com/HelipengTony)含有多个联系方式

忘记说了，还是box那边的问题（

**Comment by yzqzss** [comment]
已移至 “RSS不规范" 分类。
