### ISSUE TITLE
[TwIStOy](核桃的炼金工坊)

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#45]
ID:387
https://twistoy.com/
RSS出错...但是用工具查了下似乎...
但box那就是获取不到
![image](https://user-images.githubusercontent.com/55282876/122626620-26f77200-d0de-11eb-8135-67d6528406a0.png)
![image](https://user-images.githubusercontent.com/55282876/122626632-3b3b6f00-d0de-11eb-95e2-c1ab5f3e46af.png)

**Comment by thangpai** [comment]
查詢后屬於Box地址錯誤，Box地址為https://twistoy.com/feed。
而該部落格地址應爲：https://twistoy.com/rss.xml
