### ISSUE TITLE
[typeblog]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#46]
ID:276
https://typeblog.net/
You may be looking for https://en.typeblog.net

**Comment by gledos** [comment]
> ## 重新开始写博客
>
> 虽然有了英文博客，发布也方便得多，它仍然也只比这个中文的主博客多更新了一篇文章而已，原因也就是开头提到的那些问题。
>
> 最近也许会恢复更新博客这件事情也是最先在英文版上发布的。
>
> ......
>
> 开头已经说过，我并不再想通过老的方式来写作博客了，而且也不想使用某些写作体验更不舒服的博客方案。
>
> —— [重新开始博客: 使用 StandardNotes](https://web.archive.org/web/20190409031301/https://typeblog.net/blogging-with-standardnotes/)

这大概是主观上的关闭了博客。

#Save_The_Web_Project

**Comment by yzqzss** [comment]
移墓地了
