### ISSUE TITLE
[东方之胱] -> [木土金王可]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#51]
ID:253
https://east-bladder.com/
访问时显示east-bladder.com 的响应时间过长。
ping...大概率掉包~
![](https://i.ping.pe/8/N/img_8NZvzehx.png)

**Comment by gledos** [comment]
博主的用户名[似乎]([iMessage大产品小细节 - 知乎](https://zhuanlan.zhihu.com/p/79167351))叫 木土金王可

通过[推特](https://twitter.com/okjaketo)能找到博客地址 https://okjaketo.medium.com/

不确定「东方之胱」内容与 [Jake To – Medium](https://okjaketo.medium.com/) 相同

**Comment by 1C8199D3C9F1** [comment]
不确定与[东方之胱]内容相同。

**Comment by 1C8199D3C9F1** [comment]
博主的博客（不是新的），从Twitter找到的。
www.dujinke.com
但同样不确定是否与[东方之胱]内容相同，因为不知道当时的文章到底是什么样的。

**Comment by 1C8199D3C9F1** [comment]
您好博主，请问您的博客是从《东方之胱》改成了《木土金王可》了吗？

@okjaketo

**Comment by okjaketo** [comment]
你好，是的，我把我的博客改名成了「木土金王可」，域名也变成了 www.dujinke.com。

**Comment by yzqzss** [comment]
> 你好，是的，我把我的博客改名成了「木土金王可」，域名也变成了 www.dujinke.com。

好的👌。
