### ISSUE TITLE
[程序员小吴-一个对程序员很有用的编程网站]（原[五分钟学算法]）

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#52]
ID:199
https://www.cxyxiaowu.com/
![image](https://user-images.githubusercontent.com/55282876/122627191-91a9ad00-d0e0-11eb-92ca-1637a3e5fdce.png)
![image](https://user-images.githubusercontent.com/55282876/122627194-9ec69c00-d0e0-11eb-90b1-2c9eb6483507.png)
又一个要么rss出错要么box那边获取不到的...

**Comment by yzqzss** [comment]
移到了“RSS不规范”分类，并修改了名字:[程序员小吴]
