### ISSUE TITLE
[冰山一角]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#53]
ID:113
http://cnberg.div.io/
无法检测到whois，疑似域名被释放
~~这应该是别人提供的子域名吧...~~

**Comment by gledos** [comment]
各个社交网络账号均停止活动

+ 最后活动时间 2020-04-07 [微博](https://weibo.com/berg)
+ 最后活动时间 2020-07-30 [推特](http://twitter.com/cnberg)
+ 活动已清空 [知乎](http://www.zhihu.com/people/berg)
+ 最后活动时间 2020-07-26 微信公众号 devlife

博主曾经是 div.io 的管理员 —— [行家自述](https://www.zaih.com/falcon/mentors/2bhlovspd12)

Telegram 的 @cnberg 账号可能是博主，最近有上线，也许可以尝试联系。

**Comment by cnberg** [comment]
emmmm   文章还在呢
好吧，最近我把博客恢复吧

**Comment by cnberg** [comment]
done.

**Comment by yzqzss** [comment]
> 
> 
> done.

换域名了吗？原 cnberg.div.io 好像现在无法访问。

**Comment by cnberg** [comment]
cnberg.div.io 只是一个临时域名而已。
正式域名一直是  cnberg.com
--------------
Yours sincerely
berg
http://cnberg.com
@cnberg

**Comment by yzqzss** [comment]
> 
> cnberg.div.io 只是一个临时域名而已。 正式域名一直是 cnberg.com

有rss订阅地址吗？

**Comment by cnberg** [comment]
暂时还没有
--------------
Yours sincerely
berg
http://cnberg.com
@cnberg

**Comment by yzqzss** [comment]
box 分类已移至“不提供RSS”

**Comment by cnberg** [comment]
别慌，后面会提供的
--------------
Yours sincerely
berg
http://cnberg.com
@cnberg

**Comment by yzqzss** [comment]
> 
> 别慌，后面会提供的

好的！
