### ISSUE TITLE
[和泉日记]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#56]
ID:513
2333.tech
域名 2333.tech 正在出售！
似乎是博主看着这域名花了太多就出售了

**Comment by gledos** [comment]
> “备案了omoi.cc，想卖掉2333.tech”
>
> https://box.othing.xyz/i/?a=reader&get=f_513

似乎博主还没有将旧博客的内容搬运到新博客的计划，也许是被当作「黑历史」了吧。

### 联系方式

+ [Twitter](https://twitter.com/OMOIAKIKI) 内有邮箱

**Comment by lijiajunljj** [comment]
> > “备案了omoi.cc，想卖掉2333.tech”
> > https://box.othing.xyz/i/?a=reader&get=f_513
> 
> 似乎博主还没有将旧博客的内容搬运到新博客的计划，也许是被当作「黑历史」了吧。
> 
> ### 联系方式
> * [Twitter](https://twitter.com/OMOIAKIKI) 内有邮箱

所以也就相当于换了域名而已（）

**Comment by yzqzss** [comment]
已将 ID:513 移入墓地分类，并订阅新博客地址 ID:878
Feed: https://omoi.cc/feed/

**Comment by yzqzss** [comment]
https://github.com/saveweb/doing/issues/73

> 
> 
> 已将 ID:513 移入墓地分类，并订阅新博客地址 ID:878
> Feed: https://omoi.cc/feed/
