### ISSUE TITLE
[把酒诗代码，趁乱写年华。]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#59]
ID:180
https://102no.com/
![image](https://user-images.githubusercontent.com/55282876/122627654-873ce280-d0e3-11eb-8512-355cb9dd63c3.png)
![image](https://user-images.githubusercontent.com/55282876/122627659-8f951d80-d0e3-11eb-884e-b9b7607d028e.png)
又一个rss看起来没报错但是box那就是获取不到

**Comment by yzqzss** [comment]
box已更新Feed: http://www.102no.com/feed > https://102no.com/atom.xml
