### ISSUE TITLE
[月萌] > [无绘无会]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#61]
ID:4
https://blog.yuemoe.cn/
无法访问
![](https://i.ping.pe/9/E/img_9E5NP41P.png)

**Comment by gledos** [comment]
博主正在新建博客中

[MliKiowa/hugo](https://github.com/MliKiowa/hugo)

**Comment by yzqzss** [comment]
> 博主正在新建博客中
> 
> [MliKiowa/hugo](https://github.com/MliKiowa/hugo)

ID:4 已更新订阅: https://blog.moennar.cn/feed/

**Comment by yzqzss** [comment]
@MliKiowa 请问博主，您之前的博客（月萌）的内容是否会合并到新博客（无绘无会）里面？

**Comment by MliKiowa** [comment]
可

**Comment by MliKiowa** [comment]
> @MliKiowa 请问博主，您之前的博客（月萌）的内容是否会合并到新博客（无绘无会）里面？

内容应该不会合并了 因为那次备份数据我觉得没有价值

**Comment by yzqzss** [comment]
现在 blog.moennar.cn 无法访问，没有dns解析记录。
是在备案吗？

**Comment by MliKiowa** [comment]
正在备案 首次不允许解析
