### ISSUE TITLE
[琚致远]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#63]
ID:361
https://blog.shaoyaoju.org/
原域名会跳转到对应GitHub仓库，在仓库about那找到了新域名https://wineso.me/blog
但是没有检测到订阅链接，疑似不提供

**Comment by gledos** [comment]
> 我取关了所有公众号，这和我不喜欢公众号的 Feed 机制有关，取而代之的，订阅了相关账号的 RSS 源。
>
> —— [今天是 6 月 8 日，周一](https://wineso.me/blog/2020-06-08)

博主应该是喜欢 RSS 的，也许可以问问。

**Comment by lijiajunljj** [comment]
> > 我取关了所有公众号，这和我不喜欢公众号的 Feed 机制有关，取而代之的，订阅了相关账号的 RSS 源。
> > —— [今天是 6 月 8 日，周一](https://wineso.me/blog/2020-06-08)
> 
> 博主应该是喜欢 RSS 的，也许可以问问。

已经问了

**Comment by lijiajunljj** [comment]
> > > 我取关了所有公众号，这和我不喜欢公众号的 Feed 机制有关，取而代之的，订阅了相关账号的 RSS 源。
> > > —— [今天是 6 月 8 日，周一](https://wineso.me/blog/2020-06-08)
> > 
> > 
> > 博主应该是喜欢 RSS 的，也许可以问问。
> 
> 已经问了

回复
>短时间内还不会增加 RSS 订阅，数据源来自于 github.com/juzhiyuan/blog :) 

网站：https://wineso.me/blog
没有订阅链接
有对应上游 https://github.com/timqian/chinese-independent-blogs

**Comment by yzqzss** [comment]
![图片](https://user-images.githubusercontent.com/30341059/122668744-1df4c680-d1ec-11eb-9248-5affc44f798e.png)
先这样，等他博客有feed了再加回来。

**Comment by yzqzss** [comment]
现已提供RSS，BOX已更新。 https://wineso.me/index.xml

**Comment by juzhiyuan** [comment]
你们在干啥 🤣🤣🤣

**Comment by cronfox** [comment]
> 你们在干啥 🤣🤣🤣

你终于来了...
维护一个RSS列表(

**Comment by juzhiyuan** [comment]
😄 Thanks! 刚刚在倒腾 https://github.com/apache/apisix/projects?type=beta
