### ISSUE TITLE
[白羊李志远のBlog]（原[白羊座の漫谈]）

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#64]
ID:370
https://i-moe.eu.org/
又一个box那无法获取的...
![image](https://user-images.githubusercontent.com/55282876/122627990-e4d22e80-d0e5-11eb-84a2-a51dc919c30a.png)
![image](https://user-images.githubusercontent.com/55282876/122627978-d97f0300-d0e5-11eb-8299-06b49334892e.png)

**Comment by garfield-2001** [comment]
检查了一下。box的地址错误，应该是https://i-moe.eu.org/atom.xml，然而它指向的是https://i-moe.eu.org/feed。

**Comment by yzqzss** [comment]
好了，box已更新feed和博客名。同时pr了上游。

@baiyang-lzy 另外问下博主，您博客应该是叫做 [日常记录]/[白羊座の漫谈]/[白羊李志远]/[白羊李志远のBlog] 中的哪个名字呢？

**Comment by baiyang-lzy** [comment]
@yzqzss 应该是 “白羊李志远のBlog”，让你们费心了。

**Comment by yzqzss** [comment]
> 
> 
> @yzqzss 应该是 “白羊李志远のBlog”，让你们费心了。

好的！
