### ISSUE TITLE
[顾宇的研习笔记]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#65]
ID:303
https://www.wizardbyron.cn/
无法访问
![image](https://user-images.githubusercontent.com/55282876/122628186-53fc5280-d0e7-11eb-88e2-3a9ef914c332.png)

**Comment by gledos** [comment]
> 我把自己的博客从 Hexo 转到了 Hugos，并且部署后到了腾讯云和Github 上。前者的域名是 www.wizardbyron.cn，后者的域名是 www.guyu.me。我自己做了两个脚本分别部署。
>
> —— [2019年的总结 | 顾宇的研习笔记](https://www.guyu.me/2019/2019-12-31-annual-review-for-2019/)

域名变更， https://www.guyu.me/posts/

**Comment by lijiajunljj** [comment]
> > 我把自己的博客从 Hexo 转到了 Hugos，并且部署后到了腾讯云和Github 上。前者的域名是 [www.wizardbyron.cn，后者的域名是](http://www.wizardbyron.cn%EF%BC%8C%E5%90%8E%E8%80%85%E7%9A%84%E5%9F%9F%E5%90%8D%E6%98%AF) [www.guyu.me。我自己做了两个脚本分别部署。](http://www.guyu.me%E3%80%82%E6%88%91%E8%87%AA%E5%B7%B1%E5%81%9A%E4%BA%86%E4%B8%A4%E4%B8%AA%E8%84%9A%E6%9C%AC%E5%88%86%E5%88%AB%E9%83%A8%E7%BD%B2%E3%80%82)
> > —— [2019年的总结 | 顾宇的研习笔记](https://www.guyu.me/2019/2019-12-31-annual-review-for-2019/)
> 
> 域名变更， https://www.guyu.me/posts/

话说，有找到订阅链接吗，没的话我就去交个pr上去

**Comment by lijiajunljj** [comment]
> > > 我把自己的博客从 Hexo 转到了 Hugos，并且部署后到了腾讯云和Github 上。前者的域名是 [www.wizardbyron.cn，后者的域名是](http://www.wizardbyron.cn%EF%BC%8C%E5%90%8E%E8%80%85%E7%9A%84%E5%9F%9F%E5%90%8D%E6%98%AF) [www.guyu.me。我自己做了两个脚本分别部署。](http://www.guyu.me%E3%80%82%E6%88%91%E8%87%AA%E5%B7%B1%E5%81%9A%E4%BA%86%E4%B8%A4%E4%B8%AA%E8%84%9A%E6%9C%AC%E5%88%86%E5%88%AB%E9%83%A8%E7%BD%B2%E3%80%82)
> > > —— [2019年的总结 | 顾宇的研习笔记](https://www.guyu.me/2019/2019-12-31-annual-review-for-2019/)
> > 
> > 
> > 域名变更， https://www.guyu.me/posts/
> 
> 话说，有找到订阅链接吗，没的话我就去交个pr上去

然后似乎报错了...？
![image](https://user-images.githubusercontent.com/55282876/122635154-d8b19580-d114-11eb-919a-bfee6e61378d.png)

https://www.guyu.me/posts/index.xml

**Comment by yzqzss** [comment]
box已更新订阅，但因rss不规范，仍然保留在“rss不规范”分类
