### ISSUE TITLE
[蓝卡]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#66]
ID:216
https://www.lanka.cn/
建议移出“SSL错误”分类，目前ssl正常，但没有订阅链接

**Comment by gledos** [comment]
经测试，RSS 地址 大概是没问题 https://www.lanka.cn/feed/

**Comment by yzqzss** [comment]
也许是这个网站屏蔽了国外访问？
两台不同地区的国外vps访问这个网站都报证书错误。
![图片](https://user-images.githubusercontent.com/30341059/122642695-576ef880-d13e-11eb-88b7-693dec952284.png)

**Comment by gledos** [comment]
现在外域的加载速度似乎是很慢，不过还是能够打开

![圖片](https://user-images.githubusercontent.com/23720620/122643550-3e763100-d0c5-11eb-91c9-f1c6475460b7.png)

**Comment by yzqzss** [comment]
该网站已更换亚信的证书，现可正常解析！
