### ISSUE TITLE
[Dorole's Blog]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#67]
ID:538
https://dorole.com/
Your PHP installation appears to be missing the MySQL extension which is required by WordPress.

**Comment by gledos** [comment]
域名 Whois

> Creation Date: 2010-06-12T13:20:30Z
> Registry Expiry Date: 2022-06-12T13:20:30Z

![圖片](https://user-images.githubusercontent.com/23720620/122640994-50e96e00-d0b7-11eb-8ad0-250aff2593a5.png)

可能是没时间，博主都没有维护关于页面中的其他社交网络链接。

### 联系方式

+ https://instagram.com/_steveyang
+ mail: https://t.me/c/1356768627/1331

**Comment by lijiajunljj** [comment]
已发邮件，等待回复

**Comment by lijiajunljj** [comment]
> 已发邮件，等待回复

得到回复
>已恢复
