### ISSUE TITLE
[MOCEHU的博客]

### ISSUE THREAD

**Issue by lijiajunljj** [saveweb/doing#68]
ID:543
https://mocehu.cn/
![image](https://user-images.githubusercontent.com/55282876/122639689-cf80f280-d12d-11eb-8094-a4ac2f4f75e6.png)

**Comment by gledos** [comment]
![圖片](https://user-images.githubusercontent.com/23720620/122641214-ad995880-d0b8-11eb-8bf3-08c05e6aa1ed.png)

博客右侧仍有 RSS 链接，也许需要联系博主

**Comment by lijiajunljj** [comment]
> ![圖片](https://user-images.githubusercontent.com/23720620/122641214-ad995880-d0b8-11eb-8bf3-08c05e6aa1ed.png)
> 
> 博客右侧仍有 RSS 链接，也许需要联系博主

首页上写的是http://mocehu.cn/feed
实际上应该是https://mocehu.cn/index.php/feed/

**Comment by lijiajunljj** [comment]
已发评论，等待审核通过并回复

**Comment by lijiajunljj** [comment]
已修复

**Comment by yzqzss** [comment]
这个博客是不是又出问题了？
![图片](https://user-images.githubusercontent.com/30341059/122659446-f0d3f400-d1aa-11eb-9a65-8dc97c1b285e.png)

**Comment by gledos** [comment]
![圖片](https://user-images.githubusercontent.com/23720620/122659485-77e28700-d12d-11eb-9bed-382ce673fa08.png)

看起来我这里内地访问没有问题

**Comment by lijiajunljj** [comment]
> 这个博客是不是又出问题了？
> ![图片](https://user-images.githubusercontent.com/30341059/122659446-f0d3f400-d1aa-11eb-9a65-8dc97c1b285e.png)

我这里倒是先显示啥提示然后刷机就能看了，国内环境...我等下再测试

**Comment by garfield-2001** [comment]
网站现在正常了。

**Comment by yzqzss** [comment]
是域名DNS解析的问题，多了一条错误的A记录。博主已删。已恢复。

**Comment by 1C8199D3C9F1** [comment]
@mocehu 博主，您的博客的SSL证书过期了。

**Comment by yzqzss** [comment]
> @mocehu 博主，您的博客的SSL证书过期了。

已恢复。
