### ISSUE TITLE
[二丫讲梵]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#81]
#### 出现了什么问题：
https://wiki.eryajf.net/pages/5be3f4/
![图片](https://user-images.githubusercontent.com/30341059/127277254-2201518c-aa1a-4049-837c-80286837d0f4.png)

博主迁移了博客程序，但是新博客似乎没有rss订阅链接...

---

**Comment by yzqzss** [comment]
已询问博主: https://github.com/eryajf/eryajf.github.io/issues/151#issuecomment-888060741

**Comment by yzqzss** [comment]
https://github.com/eryajf/eryajf.github.io/issues/151#issuecomment-888172766
> 目前还没有找到好用的订阅插件，后边遇到好的插件之后会添加rss支持。

**Comment by yzqzss** [comment]
修改订阅源为：https://wiki.eryajf.net/rss.xml

**Comment by yzqzss** [comment]
@eryajf RSS还没调试好吗？ 😂

**Comment by eryajf** [comment]
> @eryajf RSS还没调试好吗？ 😂

说来惭愧，上次跟你说过之后就调试了，尝试了网上的好几个rss插件，目前都没有调试成功。
感谢你的持续关注，我会继续尝试寻找合适的rss插件，一旦成功，会与你同步！

**Comment by yzqzss** [comment]
https://github.com/timqian/chinese-independent-blogs/pull/768#issuecomment-1069192580
> 现在这个地址可以正常获取了
