### ISSUE TITLE
[Aicsukの世界]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#85]
### ID:512
https://www.aicsuk.com/
#### 出现了什么问题：
SSL过期

**Comment by yzqzss** [comment]
已发Q友申请。

**Comment by yzqzss** [comment]
再次发Q友申请。

**Comment by yzqzss** [comment]
http方式打开网站，提示：

`该网站未根据工信部相关法律规则进行备案`

---

该网站是luminous博客联盟的成员：
https://www.luminous.top/sites/56.html

**Comment by yzqzss** [comment]
域名 aicsuk.com 已于2021-10-11到期。

---
@aicsuk

**Comment by 1C8199D3C9F1** [comment]
博主貌似重新启用moe来开博客：
https://www.aicsuk.moe/

**Comment by 1C8199D3C9F1** [comment]
Feed链接有问题，里面的链接指向了127.0.0.1:2323 。

两个Feed链接：

https://www.aicsuk.moe/atom.xml

https://www.aicsuk.moe/feed

**Comment by 1C8199D3C9F1** [comment]
RSS链接已修复。

**Comment by yzqzss** [comment]
BOX已更新Feed链接为： https://www.aicsuk.moe/atom.xml
