### ISSUE TITLE
[己羊的梦]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#86]
### ID:194
https://www.jiyang00.cn/
#### 出现了什么问题：
- www.jiyang00.cn 的证书已于 2021/7/31 过期。

---
@Jiyang00

**Comment by yzqzss** [comment]
降级 http ，仍可正常访问： http://www.jiyang00.cn/

内部资料&备份：https://t.me/c/1356768627/5126
全站已上传 archive.org 。

已通过 Bilibili 私信联系博主，等待回复。

**Comment by thangpai** [comment]
貌似恢复了。

**Comment by yzqzss** [comment]
已改回 https 链接，同时移动到 “rss不规范” 分类，待  FreshRSS/FreshRSS/issues/3758 被解决后应该就能移动到正常分类了。

**Comment by yzqzss** [comment]
已改回 https 链接，同时移动到 “rss不规范” 分类，待 https://t.me/blogrsslist/297 被解决后应该就能移动到正常分类了。

**Comment by yzqzss** [comment]
网站已恢复。
分类已改回“blog|博客”

**Comment by 1C8199D3C9F1** [comment]
发生了什么问题：

`该网站未根据工信部相关法律进行备案`

**Comment by 1C8199D3C9F1** [comment]
博主，您的网站备案出了问题。

---
@Jiyang00

**Comment by 1C8199D3C9F1** [comment]
#154
