### ISSUE TITLE
[iChenH.com]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#89]
### ID:677
https://ichenh.com/
#### 出现了什么问题：
2021-08-08 域名过期。
![图片](https://user-images.githubusercontent.com/30341059/128855629-d2ff1167-1e24-468f-8d1d-02497dda948c.png)

**Comment by yzqzss** [comment]
@ichenh 博主您好，您的这个博客（ https://ichenh.com/ ），是准备关站了吗？注意到您开了一个新博客: https://www.chen.fun/

**Comment by yzqzss** [comment]
- ?-?-? chenhua.name
- 2020-08-08 iChenH.com
- 2021-01-28 chen.fun

建议域名不要经常换...

**Comment by yzqzss** [comment]
box 已将旧站（ID:677）移入墓场分类，并订阅新站（ID:639）。

**Comment by ichenh** [comment]
@yzqzss 感谢提醒！以后只用 chen.fun 这个域名。
