### ISSUE TITLE
[秋霖] > [Y同学]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#9]
ID:无
源站:https://ryani.cn/
该域名已过期释放。
archive.org有[完整快照](https://web.archive.org/web/*/https://ryani.cn/)。

已在另一个博客（应该是他朋友的博客）上通过评论[设法联系博主](https://www.strelizia.cn/index.php/default/4.html)。

**Comment by garfiled-1978** [comment]
在“另外一个博客”中点击头像鼠标右键查看那边的源代码是有博主qq的，应该可以试图使用email联系。

**Comment by yzqzss** [comment]
> 
> 
> 在“另外一个博客”中点击头像鼠标右键查看那边的源代码是有博主qq的，应该可以试图使用email联系。

已发Q友申请。

**Comment by yzqzss** [comment]
无果，进入存档流程。

**Comment by yzqzss** [comment]
https://eron.couqiao.xyz/
此博客可能为博主的新博客。名称、地址相似，且 https://www.strelizia.cn （[与该博主是朋友关系](https://github.com/saveweb/doing/issues/9#issue-919595164)）中有它的友链，且与其他博客的友链关系也与之前相似。

------

[关于这个博客&amp;建站历程 - Y同学](https://eron.couqiao.xyz/5) :
> 原来博客的一些内容以及评论也不打算迁移过来了，新的地方、重新开始。

**Comment by yzqzss** [comment]
已订阅:https://eron.couqiao.xyz/feed/
分配ID:989
