### ISSUE TITLE
[shwei's blog]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#90]
### ID:346
https://weisenhui.top
#### 出现了什么问题：
weisenhui.top 的证书已于 2021/8/8 过期。

@ugirc

**Comment by yzqzss** [comment]
已加QQ好友，已得到回复。暂时降级 http ，等待博主配置 SSL。

**Comment by yzqzss** [comment]
再提醒一下，您博客SSL还没有配置。
@ugirc

**Comment by ugirc** [comment]
> 再提醒一下，您博客SSL还没有配置。 @ugirc

您好，我不打算配置ssl了，要不把链接改成http://weisenhui.top/吧

**Comment by yzqzss** [comment]
> 
> 
> > 再提醒一下，您博客SSL还没有配置。 @ugirc
> 
> 您好，我不打算配置ssl了，要不把链接改成 http://weisenhui.top/ 吧

好！

**Comment by ugirc** [comment]
> > > 再提醒一下，您博客SSL还没有配置。 @ugirc
> > 
> > 
> > 您好，我不打算配置ssl了，要不把链接改成 http://weisenhui.top/ 吧
> 
> 好！

最近已经添加证书，可以重新使用https://weisenhui.top访问
